/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner } from "./ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner"
import {
  ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSON,
  ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSONTyped,
  ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSON,
  ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSONTyped,
} from "./ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner"
import type { ApplicationContextClassLoaderParentUnnamedModule } from "./ApplicationContextClassLoaderParentUnnamedModule"
import {
  ApplicationContextClassLoaderParentUnnamedModuleFromJSON,
  ApplicationContextClassLoaderParentUnnamedModuleFromJSONTyped,
  ApplicationContextClassLoaderParentUnnamedModuleToJSON,
  ApplicationContextClassLoaderParentUnnamedModuleToJSONTyped,
} from "./ApplicationContextClassLoaderParentUnnamedModule"
import type { ApplicationContextClassLoaderParent } from "./ApplicationContextClassLoaderParent"
import {
  ApplicationContextClassLoaderParentFromJSON,
  ApplicationContextClassLoaderParentFromJSONTyped,
  ApplicationContextClassLoaderParentToJSON,
  ApplicationContextClassLoaderParentToJSONTyped,
} from "./ApplicationContextClassLoaderParent"

/**
 *
 * @export
 * @interface ApplicationContextClassLoader
 */
export interface ApplicationContextClassLoader {
  /**
   *
   * @type {string}
   * @memberof ApplicationContextClassLoader
   */
  name?: string
  /**
   *
   * @type {boolean}
   * @memberof ApplicationContextClassLoader
   */
  registeredAsParallelCapable?: boolean
  /**
   *
   * @type {ApplicationContextClassLoaderParent}
   * @memberof ApplicationContextClassLoader
   */
  parent?: ApplicationContextClassLoaderParent
  /**
   *
   * @type {ApplicationContextClassLoaderParentUnnamedModule}
   * @memberof ApplicationContextClassLoader
   */
  unnamedModule?: ApplicationContextClassLoaderParentUnnamedModule
  /**
   *
   * @type {Array<ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner>}
   * @memberof ApplicationContextClassLoader
   */
  definedPackages?: Array<ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner>
  /**
   *
   * @type {boolean}
   * @memberof ApplicationContextClassLoader
   */
  defaultAssertionStatus?: boolean
}

/**
 * Check if a given object implements the ApplicationContextClassLoader interface.
 */
export function instanceOfApplicationContextClassLoader(
  value: object,
): value is ApplicationContextClassLoader {
  return true
}

export function ApplicationContextClassLoaderFromJSON(
  json: any,
): ApplicationContextClassLoader {
  return ApplicationContextClassLoaderFromJSONTyped(json, false)
}

export function ApplicationContextClassLoaderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApplicationContextClassLoader {
  if (json == null) {
    return json
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    registeredAsParallelCapable:
      json["registeredAsParallelCapable"] == null
        ? undefined
        : json["registeredAsParallelCapable"],
    parent:
      json["parent"] == null
        ? undefined
        : ApplicationContextClassLoaderParentFromJSON(json["parent"]),
    unnamedModule:
      json["unnamedModule"] == null
        ? undefined
        : ApplicationContextClassLoaderParentUnnamedModuleFromJSON(
            json["unnamedModule"],
          ),
    definedPackages:
      json["definedPackages"] == null
        ? undefined
        : (json["definedPackages"] as Array<any>).map(
            ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSON,
          ),
    defaultAssertionStatus:
      json["defaultAssertionStatus"] == null
        ? undefined
        : json["defaultAssertionStatus"],
  }
}

export function ApplicationContextClassLoaderToJSON(
  json: any,
): ApplicationContextClassLoader {
  return ApplicationContextClassLoaderToJSONTyped(json, false)
}

export function ApplicationContextClassLoaderToJSONTyped(
  value?: ApplicationContextClassLoader | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value["name"],
    registeredAsParallelCapable: value["registeredAsParallelCapable"],
    parent: ApplicationContextClassLoaderParentToJSON(value["parent"]),
    unnamedModule: ApplicationContextClassLoaderParentUnnamedModuleToJSON(
      value["unnamedModule"],
    ),
    definedPackages:
      value["definedPackages"] == null
        ? undefined
        : (value["definedPackages"] as Array<any>).map(
            ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSON,
          ),
    defaultAssertionStatus: value["defaultAssertionStatus"],
  }
}
