/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner } from './ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner';
import {
    ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSON,
    ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSONTyped,
    ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSON,
    ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSONTyped,
} from './ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner';
import type { ApplicationContextClassLoaderParentUnnamedModule } from './ApplicationContextClassLoaderParentUnnamedModule';
import {
    ApplicationContextClassLoaderParentUnnamedModuleFromJSON,
    ApplicationContextClassLoaderParentUnnamedModuleFromJSONTyped,
    ApplicationContextClassLoaderParentUnnamedModuleToJSON,
    ApplicationContextClassLoaderParentUnnamedModuleToJSONTyped,
} from './ApplicationContextClassLoaderParentUnnamedModule';

/**
 * 
 * @export
 * @interface ApplicationContextClassLoaderParent
 */
export interface ApplicationContextClassLoaderParent {
    /**
     * 
     * @type {string}
     * @memberof ApplicationContextClassLoaderParent
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationContextClassLoaderParent
     */
    registeredAsParallelCapable?: boolean;
    /**
     * 
     * @type {ApplicationContextClassLoaderParentUnnamedModule}
     * @memberof ApplicationContextClassLoaderParent
     */
    unnamedModule?: ApplicationContextClassLoaderParentUnnamedModule;
    /**
     * 
     * @type {Array<ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner>}
     * @memberof ApplicationContextClassLoaderParent
     */
    definedPackages?: Array<ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner>;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationContextClassLoaderParent
     */
    defaultAssertionStatus?: boolean;
}

/**
 * Check if a given object implements the ApplicationContextClassLoaderParent interface.
 */
export function instanceOfApplicationContextClassLoaderParent(value: object): value is ApplicationContextClassLoaderParent {
    return true;
}

export function ApplicationContextClassLoaderParentFromJSON(json: any): ApplicationContextClassLoaderParent {
    return ApplicationContextClassLoaderParentFromJSONTyped(json, false);
}

export function ApplicationContextClassLoaderParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationContextClassLoaderParent {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'registeredAsParallelCapable': json['registeredAsParallelCapable'] == null ? undefined : json['registeredAsParallelCapable'],
        'unnamedModule': json['unnamedModule'] == null ? undefined : ApplicationContextClassLoaderParentUnnamedModuleFromJSON(json['unnamedModule']),
        'definedPackages': json['definedPackages'] == null ? undefined : ((json['definedPackages'] as Array<any>).map(ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSON)),
        'defaultAssertionStatus': json['defaultAssertionStatus'] == null ? undefined : json['defaultAssertionStatus'],
    };
}

export function ApplicationContextClassLoaderParentToJSON(json: any): ApplicationContextClassLoaderParent {
    return ApplicationContextClassLoaderParentToJSONTyped(json, false);
}

export function ApplicationContextClassLoaderParentToJSONTyped(value?: ApplicationContextClassLoaderParent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'registeredAsParallelCapable': value['registeredAsParallelCapable'],
        'unnamedModule': ApplicationContextClassLoaderParentUnnamedModuleToJSON(value['unnamedModule']),
        'definedPackages': value['definedPackages'] == null ? undefined : ((value['definedPackages'] as Array<any>).map(ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSON)),
        'defaultAssertionStatus': value['defaultAssertionStatus'],
    };
}

