/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner } from './ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner';
import {
    ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSON,
    ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSONTyped,
    ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSON,
    ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSONTyped,
} from './ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner';

/**
 * 
 * @export
 * @interface ApplicationContextClassLoaderParentUnnamedModuleClassLoader
 */
export interface ApplicationContextClassLoaderParentUnnamedModuleClassLoader {
    /**
     * 
     * @type {string}
     * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoader
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoader
     */
    registeredAsParallelCapable?: boolean;
    /**
     * 
     * @type {Array<ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner>}
     * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoader
     */
    definedPackages?: Array<ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner>;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoader
     */
    defaultAssertionStatus?: boolean;
}

/**
 * Check if a given object implements the ApplicationContextClassLoaderParentUnnamedModuleClassLoader interface.
 */
export function instanceOfApplicationContextClassLoaderParentUnnamedModuleClassLoader(value: object): value is ApplicationContextClassLoaderParentUnnamedModuleClassLoader {
    return true;
}

export function ApplicationContextClassLoaderParentUnnamedModuleClassLoaderFromJSON(json: any): ApplicationContextClassLoaderParentUnnamedModuleClassLoader {
    return ApplicationContextClassLoaderParentUnnamedModuleClassLoaderFromJSONTyped(json, false);
}

export function ApplicationContextClassLoaderParentUnnamedModuleClassLoaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationContextClassLoaderParentUnnamedModuleClassLoader {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'registeredAsParallelCapable': json['registeredAsParallelCapable'] == null ? undefined : json['registeredAsParallelCapable'],
        'definedPackages': json['definedPackages'] == null ? undefined : ((json['definedPackages'] as Array<any>).map(ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSON)),
        'defaultAssertionStatus': json['defaultAssertionStatus'] == null ? undefined : json['defaultAssertionStatus'],
    };
}

export function ApplicationContextClassLoaderParentUnnamedModuleClassLoaderToJSON(json: any): ApplicationContextClassLoaderParentUnnamedModuleClassLoader {
    return ApplicationContextClassLoaderParentUnnamedModuleClassLoaderToJSONTyped(json, false);
}

export function ApplicationContextClassLoaderParentUnnamedModuleClassLoaderToJSONTyped(value?: ApplicationContextClassLoaderParentUnnamedModuleClassLoader | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'registeredAsParallelCapable': value['registeredAsParallelCapable'],
        'definedPackages': value['definedPackages'] == null ? undefined : ((value['definedPackages'] as Array<any>).map(ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSON)),
        'defaultAssertionStatus': value['defaultAssertionStatus'],
    };
}

