/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationContextClassLoaderParentUnnamedModuleDescriptor
 */
export interface ApplicationContextClassLoaderParentUnnamedModuleDescriptor {
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationContextClassLoaderParentUnnamedModuleDescriptor
     */
    open?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationContextClassLoaderParentUnnamedModuleDescriptor
     */
    automatic?: boolean;
}

/**
 * Check if a given object implements the ApplicationContextClassLoaderParentUnnamedModuleDescriptor interface.
 */
export function instanceOfApplicationContextClassLoaderParentUnnamedModuleDescriptor(value: object): value is ApplicationContextClassLoaderParentUnnamedModuleDescriptor {
    return true;
}

export function ApplicationContextClassLoaderParentUnnamedModuleDescriptorFromJSON(json: any): ApplicationContextClassLoaderParentUnnamedModuleDescriptor {
    return ApplicationContextClassLoaderParentUnnamedModuleDescriptorFromJSONTyped(json, false);
}

export function ApplicationContextClassLoaderParentUnnamedModuleDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationContextClassLoaderParentUnnamedModuleDescriptor {
    if (json == null) {
        return json;
    }
    return {
        
        'open': json['open'] == null ? undefined : json['open'],
        'automatic': json['automatic'] == null ? undefined : json['automatic'],
    };
}

export function ApplicationContextClassLoaderParentUnnamedModuleDescriptorToJSON(json: any): ApplicationContextClassLoaderParentUnnamedModuleDescriptor {
    return ApplicationContextClassLoaderParentUnnamedModuleDescriptorToJSONTyped(json, false);
}

export function ApplicationContextClassLoaderParentUnnamedModuleDescriptorToJSONTyped(value?: ApplicationContextClassLoaderParentUnnamedModuleDescriptor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'open': value['open'],
        'automatic': value['automatic'],
    };
}

