/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
 */
export interface ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner {
  /**
   *
   * @type {string}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  name?: string
  /**
   *
   * @type {boolean}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  sealed?: boolean
  /**
   *
   * @type {Array<object>}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  annotations?: Array<object>
  /**
   *
   * @type {Array<object>}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  declaredAnnotations?: Array<object>
  /**
   *
   * @type {string}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  specificationTitle?: string
  /**
   *
   * @type {string}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  specificationVersion?: string
  /**
   *
   * @type {string}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  specificationVendor?: string
  /**
   *
   * @type {string}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  implementationTitle?: string
  /**
   *
   * @type {string}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  implementationVersion?: string
  /**
   *
   * @type {string}
   * @memberof ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner
   */
  implementationVendor?: string
}

/**
 * Check if a given object implements the ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner interface.
 */
export function instanceOfApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner(
  value: object,
): value is ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner {
  return true
}

export function ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSON(
  json: any,
): ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner {
  return ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSONTyped(
    json,
    false,
  )
}

export function ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner {
  if (json == null) {
    return json
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    sealed: json["sealed"] == null ? undefined : json["sealed"],
    annotations: json["annotations"] == null ? undefined : json["annotations"],
    declaredAnnotations:
      json["declaredAnnotations"] == null
        ? undefined
        : json["declaredAnnotations"],
    specificationTitle:
      json["specificationTitle"] == null
        ? undefined
        : json["specificationTitle"],
    specificationVersion:
      json["specificationVersion"] == null
        ? undefined
        : json["specificationVersion"],
    specificationVendor:
      json["specificationVendor"] == null
        ? undefined
        : json["specificationVendor"],
    implementationTitle:
      json["implementationTitle"] == null
        ? undefined
        : json["implementationTitle"],
    implementationVersion:
      json["implementationVersion"] == null
        ? undefined
        : json["implementationVersion"],
    implementationVendor:
      json["implementationVendor"] == null
        ? undefined
        : json["implementationVendor"],
  }
}

export function ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSON(
  json: any,
): ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner {
  return ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSONTyped(
    json,
    false,
  )
}

export function ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInnerToJSONTyped(
  value?: ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value["name"],
    sealed: value["sealed"],
    annotations: value["annotations"],
    declaredAnnotations: value["declaredAnnotations"],
    specificationTitle: value["specificationTitle"],
    specificationVersion: value["specificationVersion"],
    specificationVendor: value["specificationVendor"],
    implementationTitle: value["implementationTitle"],
    implementationVersion: value["implementationVersion"],
    implementationVendor: value["implementationVendor"],
  }
}
