/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AreaPriceUpdateRequest
 */
export interface AreaPriceUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof AreaPriceUpdateRequest
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AreaPriceUpdateRequest
     */
    price?: number;
}

/**
 * Check if a given object implements the AreaPriceUpdateRequest interface.
 */
export function instanceOfAreaPriceUpdateRequest(value: object): value is AreaPriceUpdateRequest {
    return true;
}

export function AreaPriceUpdateRequestFromJSON(json: any): AreaPriceUpdateRequest {
    return AreaPriceUpdateRequestFromJSONTyped(json, false);
}

export function AreaPriceUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AreaPriceUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function AreaPriceUpdateRequestToJSON(json: any): AreaPriceUpdateRequest {
    return AreaPriceUpdateRequestToJSONTyped(json, false);
}

export function AreaPriceUpdateRequestToJSONTyped(value?: AreaPriceUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'price': value['price'],
    };
}

