/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface ExampleCreateRequest
 */
export interface ExampleCreateRequest {
  /**
   *
   * @type {string}
   * @memberof ExampleCreateRequest
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof ExampleCreateRequest
   */
  body: string
  /**
   *
   * @type {string}
   * @memberof ExampleCreateRequest
   */
  type?: ExampleCreateRequestTypeEnum
}

/**
 * @export
 */
export const ExampleCreateRequestTypeEnum = {
  A: "A",
  B: "B",
} as const
export type ExampleCreateRequestTypeEnum =
  (typeof ExampleCreateRequestTypeEnum)[keyof typeof ExampleCreateRequestTypeEnum]

/**
 * Check if a given object implements the ExampleCreateRequest interface.
 */
export function instanceOfExampleCreateRequest(
  value: object,
): value is ExampleCreateRequest {
  if (!("title" in value) || value["title"] === undefined) return false
  if (!("body" in value) || value["body"] === undefined) return false
  return true
}

export function ExampleCreateRequestFromJSON(json: any): ExampleCreateRequest {
  return ExampleCreateRequestFromJSONTyped(json, false)
}

export function ExampleCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExampleCreateRequest {
  if (json == null) {
    return json
  }
  return {
    title: json["title"],
    body: json["body"],
    type: json["type"] == null ? undefined : json["type"],
  }
}

export function ExampleCreateRequestToJSON(json: any): ExampleCreateRequest {
  return ExampleCreateRequestToJSONTyped(json, false)
}

export function ExampleCreateRequestToJSONTyped(
  value?: ExampleCreateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    title: value["title"],
    body: value["body"],
    type: value["type"],
  }
}
