/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface ExampleSimpleResponse
 */
export interface ExampleSimpleResponse {
  /**
   *
   * @type {number}
   * @memberof ExampleSimpleResponse
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof ExampleSimpleResponse
   */
  title?: string
}

/**
 * Check if a given object implements the ExampleSimpleResponse interface.
 */
export function instanceOfExampleSimpleResponse(
  value: object,
): value is ExampleSimpleResponse {
  return true
}

export function ExampleSimpleResponseFromJSON(
  json: any,
): ExampleSimpleResponse {
  return ExampleSimpleResponseFromJSONTyped(json, false)
}

export function ExampleSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExampleSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    title: json["title"] == null ? undefined : json["title"],
  }
}

export function ExampleSimpleResponseToJSON(json: any): ExampleSimpleResponse {
  return ExampleSimpleResponseToJSONTyped(json, false)
}

export function ExampleSimpleResponseToJSONTyped(
  value?: ExampleSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value["id"],
    title: value["title"],
  }
}
