/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExampleUpdateRequest
 */
export interface ExampleUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ExampleUpdateRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ExampleUpdateRequest
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof ExampleUpdateRequest
     */
    type: ExampleUpdateRequestTypeEnum;
}


/**
 * @export
 */
export const ExampleUpdateRequestTypeEnum = {
    A: 'A',
    B: 'B'
} as const;
export type ExampleUpdateRequestTypeEnum = typeof ExampleUpdateRequestTypeEnum[keyof typeof ExampleUpdateRequestTypeEnum];


/**
 * Check if a given object implements the ExampleUpdateRequest interface.
 */
export function instanceOfExampleUpdateRequest(value: object): value is ExampleUpdateRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ExampleUpdateRequestFromJSON(json: any): ExampleUpdateRequest {
    return ExampleUpdateRequestFromJSONTyped(json, false);
}

export function ExampleUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExampleUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'body': json['body'],
        'type': json['type'],
    };
}

export function ExampleUpdateRequestToJSON(json: any): ExampleUpdateRequest {
    return ExampleUpdateRequestToJSONTyped(json, false);
}

export function ExampleUpdateRequestToJSONTyped(value?: ExampleUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'body': value['body'],
        'type': value['type'],
    };
}

