/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberPasswordUpdateRequest
 */
export interface MemberPasswordUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof MemberPasswordUpdateRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the MemberPasswordUpdateRequest interface.
 */
export function instanceOfMemberPasswordUpdateRequest(value: object): value is MemberPasswordUpdateRequest {
    return true;
}

export function MemberPasswordUpdateRequestFromJSON(json: any): MemberPasswordUpdateRequest {
    return MemberPasswordUpdateRequestFromJSONTyped(json, false);
}

export function MemberPasswordUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberPasswordUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function MemberPasswordUpdateRequestToJSON(json: any): MemberPasswordUpdateRequest {
    return MemberPasswordUpdateRequestToJSONTyped(json, false);
}

export function MemberPasswordUpdateRequestToJSONTyped(value?: MemberPasswordUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

