/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberUpdateRequest
 */
export interface MemberUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof MemberUpdateRequest
     */
    nickname?: string;
}

/**
 * Check if a given object implements the MemberUpdateRequest interface.
 */
export function instanceOfMemberUpdateRequest(value: object): value is MemberUpdateRequest {
    return true;
}

export function MemberUpdateRequestFromJSON(json: any): MemberUpdateRequest {
    return MemberUpdateRequestFromJSONTyped(json, false);
}

export function MemberUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
    };
}

export function MemberUpdateRequestToJSON(json: any): MemberUpdateRequest {
    return MemberUpdateRequestToJSONTyped(json, false);
}

export function MemberUpdateRequestToJSONTyped(value?: MemberUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
    };
}

