/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface MemberCreateRequest
 */
export interface MemberCreateRequest {
  /**
   *
   * @type {string}
   * @memberof MemberCreateRequest
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof MemberCreateRequest
   */
  password?: string
  /**
   *
   * @type {string}
   * @memberof MemberCreateRequest
   */
  nickname?: string
}

/**
 * Check if a given object implements the MemberCreateRequest interface.
 */
export function instanceOfMemberCreateRequest(
  value: object,
): value is MemberCreateRequest {
  return true
}

export function MemberCreateRequestFromJSON(json: any): MemberCreateRequest {
  return MemberCreateRequestFromJSONTyped(json, false)
}

export function MemberCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MemberCreateRequest {
  if (json == null) {
    return json
  }
  return {
    email: json["email"] == null ? undefined : json["email"],
    password: json["password"] == null ? undefined : json["password"],
    nickname: json["nickname"] == null ? undefined : json["nickname"],
  }
}

export function MemberCreateRequestToJSON(json: any): MemberCreateRequest {
  return MemberCreateRequestToJSONTyped(json, false)
}

export function MemberCreateRequestToJSONTyped(
  value?: MemberCreateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    email: value["email"],
    password: value["password"],
    nickname: value["nickname"],
  }
}
