/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { MemberSimpleResponse } from "./MemberSimpleResponse"
import {
  MemberSimpleResponseFromJSON,
  MemberSimpleResponseFromJSONTyped,
  MemberSimpleResponseToJSON,
  MemberSimpleResponseToJSONTyped,
} from "./MemberSimpleResponse"

/**
 *
 * @export
 * @interface PageResponseMemberSimpleResponse
 */
export interface PageResponseMemberSimpleResponse {
  /**
   *
   * @type {Array<MemberSimpleResponse>}
   * @memberof PageResponseMemberSimpleResponse
   */
  items?: Array<MemberSimpleResponse>
  /**
   *
   * @type {number}
   * @memberof PageResponseMemberSimpleResponse
   */
  page?: number
  /**
   *
   * @type {number}
   * @memberof PageResponseMemberSimpleResponse
   */
  size?: number
  /**
   *
   * @type {number}
   * @memberof PageResponseMemberSimpleResponse
   */
  totalPages?: number
  /**
   *
   * @type {number}
   * @memberof PageResponseMemberSimpleResponse
   */
  totalElements?: number
}

/**
 * Check if a given object implements the PageResponseMemberSimpleResponse interface.
 */
export function instanceOfPageResponseMemberSimpleResponse(
  value: object,
): value is PageResponseMemberSimpleResponse {
  return true
}

export function PageResponseMemberSimpleResponseFromJSON(
  json: any,
): PageResponseMemberSimpleResponse {
  return PageResponseMemberSimpleResponseFromJSONTyped(json, false)
}

export function PageResponseMemberSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PageResponseMemberSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    items:
      json["items"] == null
        ? undefined
        : (json["items"] as Array<any>).map(MemberSimpleResponseFromJSON),
    page: json["page"] == null ? undefined : json["page"],
    size: json["size"] == null ? undefined : json["size"],
    totalPages: json["totalPages"] == null ? undefined : json["totalPages"],
    totalElements:
      json["totalElements"] == null ? undefined : json["totalElements"],
  }
}

export function PageResponseMemberSimpleResponseToJSON(
  json: any,
): PageResponseMemberSimpleResponse {
  return PageResponseMemberSimpleResponseToJSONTyped(json, false)
}

export function PageResponseMemberSimpleResponseToJSONTyped(
  value?: PageResponseMemberSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    items:
      value["items"] == null
        ? undefined
        : (value["items"] as Array<any>).map(MemberSimpleResponseToJSON),
    page: value["page"],
    size: value["size"],
    totalPages: value["totalPages"],
    totalElements: value["totalElements"],
  }
}
