/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExampleSimpleResponse } from './ExampleSimpleResponse';
import {
    ExampleSimpleResponseFromJSON,
    ExampleSimpleResponseFromJSONTyped,
    ExampleSimpleResponseToJSON,
    ExampleSimpleResponseToJSONTyped,
} from './ExampleSimpleResponse';

/**
 * 
 * @export
 * @interface PageResponseExampleSimpleResponse
 */
export interface PageResponseExampleSimpleResponse {
    /**
     * 
     * @type {Array<ExampleSimpleResponse>}
     * @memberof PageResponseExampleSimpleResponse
     */
    items?: Array<ExampleSimpleResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseExampleSimpleResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseExampleSimpleResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseExampleSimpleResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseExampleSimpleResponse
     */
    totalElements?: number;
}

/**
 * Check if a given object implements the PageResponseExampleSimpleResponse interface.
 */
export function instanceOfPageResponseExampleSimpleResponse(value: object): value is PageResponseExampleSimpleResponse {
    return true;
}

export function PageResponseExampleSimpleResponseFromJSON(json: any): PageResponseExampleSimpleResponse {
    return PageResponseExampleSimpleResponseFromJSONTyped(json, false);
}

export function PageResponseExampleSimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseExampleSimpleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ExampleSimpleResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
    };
}

export function PageResponseExampleSimpleResponseToJSON(json: any): PageResponseExampleSimpleResponse {
    return PageResponseExampleSimpleResponseToJSONTyped(json, false);
}

export function PageResponseExampleSimpleResponseToJSONTyped(value?: PageResponseExampleSimpleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ExampleSimpleResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
    };
}

