/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostSimpleResponse } from './PostSimpleResponse';
import {
    PostSimpleResponseFromJSON,
    PostSimpleResponseFromJSONTyped,
    PostSimpleResponseToJSON,
    PostSimpleResponseToJSONTyped,
} from './PostSimpleResponse';

/**
 * 
 * @export
 * @interface PageResponsePostSimpleResponse
 */
export interface PageResponsePostSimpleResponse {
    /**
     * 
     * @type {Array<PostSimpleResponse>}
     * @memberof PageResponsePostSimpleResponse
     */
    items?: Array<PostSimpleResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponsePostSimpleResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponsePostSimpleResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponsePostSimpleResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponsePostSimpleResponse
     */
    totalElements?: number;
}

/**
 * Check if a given object implements the PageResponsePostSimpleResponse interface.
 */
export function instanceOfPageResponsePostSimpleResponse(value: object): value is PageResponsePostSimpleResponse {
    return true;
}

export function PageResponsePostSimpleResponseFromJSON(json: any): PageResponsePostSimpleResponse {
    return PageResponsePostSimpleResponseFromJSONTyped(json, false);
}

export function PageResponsePostSimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponsePostSimpleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(PostSimpleResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
    };
}

export function PageResponsePostSimpleResponseToJSON(json: any): PageResponsePostSimpleResponse {
    return PageResponsePostSimpleResponseToJSONTyped(json, false);
}

export function PageResponsePostSimpleResponseToJSONTyped(value?: PageResponsePostSimpleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(PostSimpleResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
    };
}

