/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { PaymentSimpleResponse } from "./PaymentSimpleResponse"
import {
  PaymentSimpleResponseFromJSON,
  PaymentSimpleResponseFromJSONTyped,
  PaymentSimpleResponseToJSON,
  PaymentSimpleResponseToJSONTyped,
} from "./PaymentSimpleResponse"

/**
 *
 * @export
 * @interface PageResponsePaymentSimpleResponse
 */
export interface PageResponsePaymentSimpleResponse {
  /**
   *
   * @type {Array<PaymentSimpleResponse>}
   * @memberof PageResponsePaymentSimpleResponse
   */
  items?: Array<PaymentSimpleResponse>
  /**
   *
   * @type {number}
   * @memberof PageResponsePaymentSimpleResponse
   */
  page?: number
  /**
   *
   * @type {number}
   * @memberof PageResponsePaymentSimpleResponse
   */
  size?: number
  /**
   *
   * @type {number}
   * @memberof PageResponsePaymentSimpleResponse
   */
  totalPages?: number
  /**
   *
   * @type {number}
   * @memberof PageResponsePaymentSimpleResponse
   */
  totalElements?: number
}

/**
 * Check if a given object implements the PageResponsePaymentSimpleResponse interface.
 */
export function instanceOfPageResponsePaymentSimpleResponse(
  value: object,
): value is PageResponsePaymentSimpleResponse {
  return true
}

export function PageResponsePaymentSimpleResponseFromJSON(
  json: any,
): PageResponsePaymentSimpleResponse {
  return PageResponsePaymentSimpleResponseFromJSONTyped(json, false)
}

export function PageResponsePaymentSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PageResponsePaymentSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    items:
      json["items"] == null
        ? undefined
        : (json["items"] as Array<any>).map(PaymentSimpleResponseFromJSON),
    page: json["page"] == null ? undefined : json["page"],
    size: json["size"] == null ? undefined : json["size"],
    totalPages: json["totalPages"] == null ? undefined : json["totalPages"],
    totalElements:
      json["totalElements"] == null ? undefined : json["totalElements"],
  }
}

export function PageResponsePaymentSimpleResponseToJSON(
  json: any,
): PageResponsePaymentSimpleResponse {
  return PageResponsePaymentSimpleResponseToJSONTyped(json, false)
}

export function PageResponsePaymentSimpleResponseToJSONTyped(
  value?: PageResponsePaymentSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    items:
      value["items"] == null
        ? undefined
        : (value["items"] as Array<any>).map(PaymentSimpleResponseToJSON),
    page: value["page"],
    size: value["size"],
    totalPages: value["totalPages"],
    totalElements: value["totalElements"],
  }
}
