/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { ReservationLogResponse } from "./ReservationLogResponse"
import {
  ReservationLogResponseFromJSON,
  ReservationLogResponseFromJSONTyped,
  ReservationLogResponseToJSON,
  ReservationLogResponseToJSONTyped,
} from "./ReservationLogResponse"

/**
 *
 * @export
 * @interface PageResponseReservationLogResponse
 */
export interface PageResponseReservationLogResponse {
  /**
   *
   * @type {Array<ReservationLogResponse>}
   * @memberof PageResponseReservationLogResponse
   */
  items?: Array<ReservationLogResponse>
  /**
   *
   * @type {number}
   * @memberof PageResponseReservationLogResponse
   */
  page?: number
  /**
   *
   * @type {number}
   * @memberof PageResponseReservationLogResponse
   */
  size?: number
  /**
   *
   * @type {number}
   * @memberof PageResponseReservationLogResponse
   */
  totalPages?: number
  /**
   *
   * @type {number}
   * @memberof PageResponseReservationLogResponse
   */
  totalElements?: number
}

/**
 * Check if a given object implements the PageResponseReservationLogResponse interface.
 */
export function instanceOfPageResponseReservationLogResponse(
  value: object,
): value is PageResponseReservationLogResponse {
  return true
}

export function PageResponseReservationLogResponseFromJSON(
  json: any,
): PageResponseReservationLogResponse {
  return PageResponseReservationLogResponseFromJSONTyped(json, false)
}

export function PageResponseReservationLogResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PageResponseReservationLogResponse {
  if (json == null) {
    return json
  }
  return {
    items:
      json["items"] == null
        ? undefined
        : (json["items"] as Array<any>).map(ReservationLogResponseFromJSON),
    page: json["page"] == null ? undefined : json["page"],
    size: json["size"] == null ? undefined : json["size"],
    totalPages: json["totalPages"] == null ? undefined : json["totalPages"],
    totalElements:
      json["totalElements"] == null ? undefined : json["totalElements"],
  }
}

export function PageResponseReservationLogResponseToJSON(
  json: any,
): PageResponseReservationLogResponse {
  return PageResponseReservationLogResponseToJSONTyped(json, false)
}

export function PageResponseReservationLogResponseToJSONTyped(
  value?: PageResponseReservationLogResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    items:
      value["items"] == null
        ? undefined
        : (value["items"] as Array<any>).map(ReservationLogResponseToJSON),
    page: value["page"],
    size: value["size"],
    totalPages: value["totalPages"],
    totalElements: value["totalElements"],
  }
}
