/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationSimpleResponse } from './ReservationSimpleResponse';
import {
    ReservationSimpleResponseFromJSON,
    ReservationSimpleResponseFromJSONTyped,
    ReservationSimpleResponseToJSON,
    ReservationSimpleResponseToJSONTyped,
} from './ReservationSimpleResponse';

/**
 * 
 * @export
 * @interface PageResponseReservationSimpleResponse
 */
export interface PageResponseReservationSimpleResponse {
    /**
     * 
     * @type {Array<ReservationSimpleResponse>}
     * @memberof PageResponseReservationSimpleResponse
     */
    items?: Array<ReservationSimpleResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseReservationSimpleResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseReservationSimpleResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseReservationSimpleResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseReservationSimpleResponse
     */
    totalElements?: number;
}

/**
 * Check if a given object implements the PageResponseReservationSimpleResponse interface.
 */
export function instanceOfPageResponseReservationSimpleResponse(value: object): value is PageResponseReservationSimpleResponse {
    return true;
}

export function PageResponseReservationSimpleResponseFromJSON(json: any): PageResponseReservationSimpleResponse {
    return PageResponseReservationSimpleResponseFromJSONTyped(json, false);
}

export function PageResponseReservationSimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseReservationSimpleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ReservationSimpleResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
    };
}

export function PageResponseReservationSimpleResponseToJSON(json: any): PageResponseReservationSimpleResponse {
    return PageResponseReservationSimpleResponseToJSONTyped(json, false);
}

export function PageResponseReservationSimpleResponseToJSONTyped(value?: PageResponseReservationSimpleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ReservationSimpleResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
    };
}

