/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { PaymentLogResponse } from "./PaymentLogResponse"
import {
  PaymentLogResponseFromJSON,
  PaymentLogResponseFromJSONTyped,
  PaymentLogResponseToJSON,
  PaymentLogResponseToJSONTyped,
} from "./PaymentLogResponse"

/**
 *
 * @export
 * @interface PageResponsePaymentLogResponse
 */
export interface PageResponsePaymentLogResponse {
  /**
   *
   * @type {Array<PaymentLogResponse>}
   * @memberof PageResponsePaymentLogResponse
   */
  items?: Array<PaymentLogResponse>
  /**
   *
   * @type {number}
   * @memberof PageResponsePaymentLogResponse
   */
  page?: number
  /**
   *
   * @type {number}
   * @memberof PageResponsePaymentLogResponse
   */
  size?: number
  /**
   *
   * @type {number}
   * @memberof PageResponsePaymentLogResponse
   */
  totalPages?: number
  /**
   *
   * @type {number}
   * @memberof PageResponsePaymentLogResponse
   */
  totalElements?: number
}

/**
 * Check if a given object implements the PageResponsePaymentLogResponse interface.
 */
export function instanceOfPageResponsePaymentLogResponse(
  value: object,
): value is PageResponsePaymentLogResponse {
  return true
}

export function PageResponsePaymentLogResponseFromJSON(
  json: any,
): PageResponsePaymentLogResponse {
  return PageResponsePaymentLogResponseFromJSONTyped(json, false)
}

export function PageResponsePaymentLogResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PageResponsePaymentLogResponse {
  if (json == null) {
    return json
  }
  return {
    items:
      json["items"] == null
        ? undefined
        : (json["items"] as Array<any>).map(PaymentLogResponseFromJSON),
    page: json["page"] == null ? undefined : json["page"],
    size: json["size"] == null ? undefined : json["size"],
    totalPages: json["totalPages"] == null ? undefined : json["totalPages"],
    totalElements:
      json["totalElements"] == null ? undefined : json["totalElements"],
  }
}

export function PageResponsePaymentLogResponseToJSON(
  json: any,
): PageResponsePaymentLogResponse {
  return PageResponsePaymentLogResponseToJSONTyped(json, false)
}

export function PageResponsePaymentLogResponseToJSONTyped(
  value?: PageResponsePaymentLogResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    items:
      value["items"] == null
        ? undefined
        : (value["items"] as Array<any>).map(PaymentLogResponseToJSON),
    page: value["page"],
    size: value["size"],
    totalPages: value["totalPages"],
    totalElements: value["totalElements"],
  }
}
