/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface PaymentDetailResponse
 */
export interface PaymentDetailResponse {
  /**
   *
   * @type {number}
   * @memberof PaymentDetailResponse
   */
  id?: number
  /**
   *
   * @type {number}
   * @memberof PaymentDetailResponse
   */
  amount?: number
  /**
   *
   * @type {string}
   * @memberof PaymentDetailResponse
   */
  orderId?: string
  /**
   *
   * @type {number}
   * @memberof PaymentDetailResponse
   */
  reservationId?: number
  /**
   *
   * @type {string}
   * @memberof PaymentDetailResponse
   */
  performanceName?: string
  /**
   *
   * @type {string}
   * @memberof PaymentDetailResponse
   */
  paymentStatus?: PaymentDetailResponsePaymentStatusEnum
  /**
   *
   * @type {Date}
   * @memberof PaymentDetailResponse
   */
  createdAt?: Date
}

/**
 * @export
 */
export const PaymentDetailResponsePaymentStatusEnum = {
  Pending: "PENDING",
  Completed: "COMPLETED",
  Failed: "FAILED",
  Canceled: "CANCELED",
  Expired: "EXPIRED",
} as const
export type PaymentDetailResponsePaymentStatusEnum =
  (typeof PaymentDetailResponsePaymentStatusEnum)[keyof typeof PaymentDetailResponsePaymentStatusEnum]

/**
 * Check if a given object implements the PaymentDetailResponse interface.
 */
export function instanceOfPaymentDetailResponse(
  value: object,
): value is PaymentDetailResponse {
  return true
}

export function PaymentDetailResponseFromJSON(
  json: any,
): PaymentDetailResponse {
  return PaymentDetailResponseFromJSONTyped(json, false)
}

export function PaymentDetailResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaymentDetailResponse {
  if (json == null) {
    return json
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    amount: json["amount"] == null ? undefined : json["amount"],
    orderId: json["orderId"] == null ? undefined : json["orderId"],
    reservationId:
      json["reservationId"] == null ? undefined : json["reservationId"],
    performanceName:
      json["performanceName"] == null ? undefined : json["performanceName"],
    paymentStatus:
      json["paymentStatus"] == null ? undefined : json["paymentStatus"],
    createdAt:
      json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
  }
}

export function PaymentDetailResponseToJSON(json: any): PaymentDetailResponse {
  return PaymentDetailResponseToJSONTyped(json, false)
}

export function PaymentDetailResponseToJSONTyped(
  value?: PaymentDetailResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value["id"],
    amount: value["amount"],
    orderId: value["orderId"],
    reservationId: value["reservationId"],
    performanceName: value["performanceName"],
    paymentStatus: value["paymentStatus"],
    createdAt:
      value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
  }
}
