/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface PaymentConfirmRequest
 */
export interface PaymentConfirmRequest {
  /**
   *
   * @type {string}
   * @memberof PaymentConfirmRequest
   */
  paymentKey?: string
  /**
   *
   * @type {string}
   * @memberof PaymentConfirmRequest
   */
  orderId?: string
  /**
   *
   * @type {number}
   * @memberof PaymentConfirmRequest
   */
  amount: number
}

/**
 * Check if a given object implements the PaymentConfirmRequest interface.
 */
export function instanceOfPaymentConfirmRequest(
  value: object,
): value is PaymentConfirmRequest {
  if (!("amount" in value) || value["amount"] === undefined) return false
  return true
}

export function PaymentConfirmRequestFromJSON(
  json: any,
): PaymentConfirmRequest {
  return PaymentConfirmRequestFromJSONTyped(json, false)
}

export function PaymentConfirmRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaymentConfirmRequest {
  if (json == null) {
    return json
  }
  return {
    paymentKey: json["paymentKey"] == null ? undefined : json["paymentKey"],
    orderId: json["orderId"] == null ? undefined : json["orderId"],
    amount: json["amount"],
  }
}

export function PaymentConfirmRequestToJSON(json: any): PaymentConfirmRequest {
  return PaymentConfirmRequestToJSONTyped(json, false)
}

export function PaymentConfirmRequestToJSONTyped(
  value?: PaymentConfirmRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    paymentKey: value["paymentKey"],
    orderId: value["orderId"],
    amount: value["amount"],
  }
}
