/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface PaymentCreateRequest
 */
export interface PaymentCreateRequest {
  /**
   *
   * @type {number}
   * @memberof PaymentCreateRequest
   */
  amount: number
  /**
   *
   * @type {number}
   * @memberof PaymentCreateRequest
   */
  reservationId: number
}

/**
 * Check if a given object implements the PaymentCreateRequest interface.
 */
export function instanceOfPaymentCreateRequest(
  value: object,
): value is PaymentCreateRequest {
  if (!("amount" in value) || value["amount"] === undefined) return false
  if (!("reservationId" in value) || value["reservationId"] === undefined)
    return false
  return true
}

export function PaymentCreateRequestFromJSON(json: any): PaymentCreateRequest {
  return PaymentCreateRequestFromJSONTyped(json, false)
}

export function PaymentCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaymentCreateRequest {
  if (json == null) {
    return json
  }
  return {
    amount: json["amount"],
    reservationId: json["reservationId"],
  }
}

export function PaymentCreateRequestToJSON(json: any): PaymentCreateRequest {
  return PaymentCreateRequestToJSONTyped(json, false)
}

export function PaymentCreateRequestToJSONTyped(
  value?: PaymentCreateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    amount: value["amount"],
    reservationId: value["reservationId"],
  }
}
