/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceSessionResponse
 */
export interface PerformanceSessionResponse {
    /**
     * 
     * @type {number}
     * @memberof PerformanceSessionResponse
     */
    performanceSessionId?: number;
    /**
     * 
     * @type {Date}
     * @memberof PerformanceSessionResponse
     */
    performanceTime?: Date;
}

/**
 * Check if a given object implements the PerformanceSessionResponse interface.
 */
export function instanceOfPerformanceSessionResponse(value: object): value is PerformanceSessionResponse {
    return true;
}

export function PerformanceSessionResponseFromJSON(json: any): PerformanceSessionResponse {
    return PerformanceSessionResponseFromJSONTyped(json, false);
}

export function PerformanceSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'performanceSessionId': json['performance_session_id'] == null ? undefined : json['performance_session_id'],
        'performanceTime': json['performance_time'] == null ? undefined : (new Date(json['performance_time'])),
    };
}

export function PerformanceSessionResponseToJSON(json: any): PerformanceSessionResponse {
    return PerformanceSessionResponseToJSONTyped(json, false);
}

export function PerformanceSessionResponseToJSONTyped(value?: PerformanceSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'performance_session_id': value['performanceSessionId'],
        'performance_time': value['performanceTime'] == null ? undefined : ((value['performanceTime']).toISOString()),
    };
}

