/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceSessionResponse
 */
export interface PerformanceSessionResponse {
    /**
     * 
     * @type {number}
     * @memberof PerformanceSessionResponse
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PerformanceSessionResponse
     */
    time?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PerformanceSessionResponse
     */
    reserveOpenAt?: Date;
}

/**
 * Check if a given object implements the PerformanceSessionResponse interface.
 */
export function instanceOfPerformanceSessionResponse(value: object): value is PerformanceSessionResponse {
    return true;
}

export function PerformanceSessionResponseFromJSON(json: any): PerformanceSessionResponse {
    return PerformanceSessionResponseFromJSONTyped(json, false);
}

export function PerformanceSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'reserveOpenAt': json['reserveOpenAt'] == null ? undefined : (new Date(json['reserveOpenAt'])),
    };
}

export function PerformanceSessionResponseToJSON(json: any): PerformanceSessionResponse {
    return PerformanceSessionResponseToJSONTyped(json, false);
}

export function PerformanceSessionResponseToJSONTyped(value?: PerformanceSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'reserveOpenAt': value['reserveOpenAt'] == null ? undefined : ((value['reserveOpenAt']).toISOString()),
    };
}

