/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { AreaPriceUpdateRequest } from "./AreaPriceUpdateRequest"
import {
  AreaPriceUpdateRequestFromJSON,
  AreaPriceUpdateRequestFromJSONTyped,
  AreaPriceUpdateRequestToJSON,
  AreaPriceUpdateRequestToJSONTyped,
} from "./AreaPriceUpdateRequest"
import type { VenueRequest } from "./VenueRequest"
import {
  VenueRequestFromJSON,
  VenueRequestFromJSONTyped,
  VenueRequestToJSON,
  VenueRequestToJSONTyped,
} from "./VenueRequest"

/**
 *
 * @export
 * @interface PerformanceUpdateRequest
 */
export interface PerformanceUpdateRequest {
  /**
   *
   * @type {number}
   * @memberof PerformanceUpdateRequest
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof PerformanceUpdateRequest
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceUpdateRequest
   */
  poster?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceUpdateRequest
   */
  overview?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceUpdateRequest
   */
  state?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceUpdateRequest
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceUpdateRequest
   */
  casts?: string
  /**
   *
   * @type {Date}
   * @memberof PerformanceUpdateRequest
   */
  startDate?: Date
  /**
   *
   * @type {Date}
   * @memberof PerformanceUpdateRequest
   */
  endDate?: Date
  /**
   *
   * @type {number}
   * @memberof PerformanceUpdateRequest
   */
  runtime?: number
  /**
   *
   * @type {number}
   * @memberof PerformanceUpdateRequest
   */
  minAge?: number
  /**
   *
   * @type {VenueRequest}
   * @memberof PerformanceUpdateRequest
   */
  venue?: VenueRequest
  /**
   *
   * @type {Array<AreaPriceUpdateRequest>}
   * @memberof PerformanceUpdateRequest
   */
  areas?: Array<AreaPriceUpdateRequest>
  /**
   *
   * @type {Array<string>}
   * @memberof PerformanceUpdateRequest
   */
  introImages?: Array<string>
}

/**
 * Check if a given object implements the PerformanceUpdateRequest interface.
 */
export function instanceOfPerformanceUpdateRequest(
  value: object,
): value is PerformanceUpdateRequest {
  return true
}

export function PerformanceUpdateRequestFromJSON(
  json: any,
): PerformanceUpdateRequest {
  return PerformanceUpdateRequestFromJSONTyped(json, false)
}

export function PerformanceUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PerformanceUpdateRequest {
  if (json == null) {
    return json
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    poster: json["poster"] == null ? undefined : json["poster"],
    overview: json["overview"] == null ? undefined : json["overview"],
    state: json["state"] == null ? undefined : json["state"],
    type: json["type"] == null ? undefined : json["type"],
    casts: json["casts"] == null ? undefined : json["casts"],
    startDate:
      json["startDate"] == null ? undefined : new Date(json["startDate"]),
    endDate: json["endDate"] == null ? undefined : new Date(json["endDate"]),
    runtime: json["runtime"] == null ? undefined : json["runtime"],
    minAge: json["minAge"] == null ? undefined : json["minAge"],
    venue:
      json["venue"] == null ? undefined : VenueRequestFromJSON(json["venue"]),
    areas:
      json["areas"] == null
        ? undefined
        : (json["areas"] as Array<any>).map(AreaPriceUpdateRequestFromJSON),
    introImages: json["introImages"] == null ? undefined : json["introImages"],
  }
}

export function PerformanceUpdateRequestToJSON(
  json: any,
): PerformanceUpdateRequest {
  return PerformanceUpdateRequestToJSONTyped(json, false)
}

export function PerformanceUpdateRequestToJSONTyped(
  value?: PerformanceUpdateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value["id"],
    name: value["name"],
    poster: value["poster"],
    overview: value["overview"],
    state: value["state"],
    type: value["type"],
    casts: value["casts"],
    startDate:
      value["startDate"] == null ? undefined : value["startDate"].toISOString(),
    endDate:
      value["endDate"] == null ? undefined : value["endDate"].toISOString(),
    runtime: value["runtime"],
    minAge: value["minAge"],
    venue: VenueRequestToJSON(value["venue"]),
    areas:
      value["areas"] == null
        ? undefined
        : (value["areas"] as Array<any>).map(AreaPriceUpdateRequestToJSON),
    introImages: value["introImages"],
  }
}
