/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceSessionInfo
 */
export interface PerformanceSessionInfo {
    /**
     * 
     * @type {number}
     * @memberof PerformanceSessionInfo
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PerformanceSessionInfo
     */
    performanceTime?: Date;
}

/**
 * Check if a given object implements the PerformanceSessionInfo interface.
 */
export function instanceOfPerformanceSessionInfo(value: object): value is PerformanceSessionInfo {
    return true;
}

export function PerformanceSessionInfoFromJSON(json: any): PerformanceSessionInfo {
    return PerformanceSessionInfoFromJSONTyped(json, false);
}

export function PerformanceSessionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceSessionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'performanceTime': json['performanceTime'] == null ? undefined : (new Date(json['performanceTime'])),
    };
}

export function PerformanceSessionInfoToJSON(json: any): PerformanceSessionInfo {
    return PerformanceSessionInfoToJSONTyped(json, false);
}

export function PerformanceSessionInfoToJSONTyped(value?: PerformanceSessionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'performanceTime': value['performanceTime'] == null ? undefined : ((value['performanceTime']).toISOString()),
    };
}

