/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceInfo
 */
export interface PerformanceInfo {
    /**
     * 
     * @type {string}
     * @memberof PerformanceInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceInfo
     */
    poster?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceInfo
     */
    runtime?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceInfo
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceInfo
     */
    state?: string;
}

/**
 * Check if a given object implements the PerformanceInfo interface.
 */
export function instanceOfPerformanceInfo(value: object): value is PerformanceInfo {
    return true;
}

export function PerformanceInfoFromJSON(json: any): PerformanceInfo {
    return PerformanceInfoFromJSONTyped(json, false);
}

export function PerformanceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'poster': json['poster'] == null ? undefined : json['poster'],
        'runtime': json['runtime'] == null ? undefined : json['runtime'],
        'type': json['type'] == null ? undefined : json['type'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function PerformanceInfoToJSON(json: any): PerformanceInfo {
    return PerformanceInfoToJSONTyped(json, false);
}

export function PerformanceInfoToJSONTyped(value?: PerformanceInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'poster': value['poster'],
        'runtime': value['runtime'],
        'type': value['type'],
        'state': value['state'],
    };
}

