/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceAreaResponse
 */
export interface PerformanceAreaResponse {
    /**
     * 
     * @type {number}
     * @memberof PerformanceAreaResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PerformanceAreaResponse
     */
    name?: PerformanceAreaResponseNameEnum;
    /**
     * 
     * @type {string}
     * @memberof PerformanceAreaResponse
     */
    grade?: PerformanceAreaResponseGradeEnum;
    /**
     * 
     * @type {number}
     * @memberof PerformanceAreaResponse
     */
    price?: number;
}


/**
 * @export
 */
export const PerformanceAreaResponseNameEnum = {
    Vip: 'VIP',
    A: 'A',
    B: 'B',
    C: 'C',
    D: 'D'
} as const;
export type PerformanceAreaResponseNameEnum = typeof PerformanceAreaResponseNameEnum[keyof typeof PerformanceAreaResponseNameEnum];

/**
 * @export
 */
export const PerformanceAreaResponseGradeEnum = {
    Premium: 'PREMIUM',
    Royal: 'ROYAL',
    Special: 'SPECIAL',
    Normal: 'NORMAL'
} as const;
export type PerformanceAreaResponseGradeEnum = typeof PerformanceAreaResponseGradeEnum[keyof typeof PerformanceAreaResponseGradeEnum];


/**
 * Check if a given object implements the PerformanceAreaResponse interface.
 */
export function instanceOfPerformanceAreaResponse(value: object): value is PerformanceAreaResponse {
    return true;
}

export function PerformanceAreaResponseFromJSON(json: any): PerformanceAreaResponse {
    return PerformanceAreaResponseFromJSONTyped(json, false);
}

export function PerformanceAreaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceAreaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'grade': json['grade'] == null ? undefined : json['grade'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function PerformanceAreaResponseToJSON(json: any): PerformanceAreaResponse {
    return PerformanceAreaResponseToJSONTyped(json, false);
}

export function PerformanceAreaResponseToJSONTyped(value?: PerformanceAreaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'grade': value['grade'],
        'price': value['price'],
    };
}

