/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { VenueResponse } from "./VenueResponse"
import {
  VenueResponseFromJSON,
  VenueResponseFromJSONTyped,
  VenueResponseToJSON,
  VenueResponseToJSONTyped,
} from "./VenueResponse"
import type { PerformanceSessionResponse } from "./PerformanceSessionResponse"
import {
  PerformanceSessionResponseFromJSON,
  PerformanceSessionResponseFromJSONTyped,
  PerformanceSessionResponseToJSON,
  PerformanceSessionResponseToJSONTyped,
} from "./PerformanceSessionResponse"
import type { PerformanceAreaSimpleResponse } from "./PerformanceAreaSimpleResponse"
import {
  PerformanceAreaSimpleResponseFromJSON,
  PerformanceAreaSimpleResponseFromJSONTyped,
  PerformanceAreaSimpleResponseToJSON,
  PerformanceAreaSimpleResponseToJSONTyped,
} from "./PerformanceAreaSimpleResponse"

/**
 *
 * @export
 * @interface PerformanceDetailResponse
 */
export interface PerformanceDetailResponse {
  /**
   *
   * @type {number}
   * @memberof PerformanceDetailResponse
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof PerformanceDetailResponse
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceDetailResponse
   */
  poster?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceDetailResponse
   */
  state?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceDetailResponse
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceDetailResponse
   */
  casts?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceDetailResponse
   */
  runtime?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceDetailResponse
   */
  minAge?: string
  /**
   *
   * @type {Date}
   * @memberof PerformanceDetailResponse
   */
  startDate?: Date
  /**
   *
   * @type {Date}
   * @memberof PerformanceDetailResponse
   */
  endDate?: Date
  /**
   *
   * @type {VenueResponse}
   * @memberof PerformanceDetailResponse
   */
  venue?: VenueResponse
  /**
   *
   * @type {Array<string>}
   * @memberof PerformanceDetailResponse
   */
  images?: Array<string>
  /**
   *
   * @type {Array<PerformanceAreaSimpleResponse>}
   * @memberof PerformanceDetailResponse
   */
  areas?: Array<PerformanceAreaSimpleResponse>
  /**
   *
   * @type {Array<PerformanceSessionResponse>}
   * @memberof PerformanceDetailResponse
   */
  sessions?: Array<PerformanceSessionResponse>
}

/**
 * Check if a given object implements the PerformanceDetailResponse interface.
 */
export function instanceOfPerformanceDetailResponse(
  value: object,
): value is PerformanceDetailResponse {
  return true
}

export function PerformanceDetailResponseFromJSON(
  json: any,
): PerformanceDetailResponse {
  return PerformanceDetailResponseFromJSONTyped(json, false)
}

export function PerformanceDetailResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PerformanceDetailResponse {
  if (json == null) {
    return json
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    poster: json["poster"] == null ? undefined : json["poster"],
    state: json["state"] == null ? undefined : json["state"],
    type: json["type"] == null ? undefined : json["type"],
    casts: json["casts"] == null ? undefined : json["casts"],
    runtime: json["runtime"] == null ? undefined : json["runtime"],
    minAge: json["minAge"] == null ? undefined : json["minAge"],
    startDate:
      json["startDate"] == null ? undefined : new Date(json["startDate"]),
    endDate: json["endDate"] == null ? undefined : new Date(json["endDate"]),
    venue:
      json["venue"] == null ? undefined : VenueResponseFromJSON(json["venue"]),
    images: json["images"] == null ? undefined : json["images"],
    areas:
      json["areas"] == null
        ? undefined
        : (json["areas"] as Array<any>).map(
            PerformanceAreaSimpleResponseFromJSON,
          ),
    sessions:
      json["sessions"] == null
        ? undefined
        : (json["sessions"] as Array<any>).map(
            PerformanceSessionResponseFromJSON,
          ),
  }
}

export function PerformanceDetailResponseToJSON(
  json: any,
): PerformanceDetailResponse {
  return PerformanceDetailResponseToJSONTyped(json, false)
}

export function PerformanceDetailResponseToJSONTyped(
  value?: PerformanceDetailResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value["id"],
    name: value["name"],
    poster: value["poster"],
    state: value["state"],
    type: value["type"],
    casts: value["casts"],
    runtime: value["runtime"],
    minAge: value["minAge"],
    startDate:
      value["startDate"] == null
        ? undefined
        : value["startDate"].toISOString().substring(0, 10),
    endDate:
      value["endDate"] == null
        ? undefined
        : value["endDate"].toISOString().substring(0, 10),
    venue: VenueResponseToJSON(value["venue"]),
    images: value["images"],
    areas:
      value["areas"] == null
        ? undefined
        : (value["areas"] as Array<any>).map(
            PerformanceAreaSimpleResponseToJSON,
          ),
    sessions:
      value["sessions"] == null
        ? undefined
        : (value["sessions"] as Array<any>).map(
            PerformanceSessionResponseToJSON,
          ),
  }
}
