/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { SeatSimpleResponse } from "./SeatSimpleResponse"
import {
  SeatSimpleResponseFromJSON,
  SeatSimpleResponseFromJSONTyped,
  SeatSimpleResponseToJSON,
  SeatSimpleResponseToJSONTyped,
} from "./SeatSimpleResponse"

/**
 *
 * @export
 * @interface PerformanceAreaDetailResponse
 */
export interface PerformanceAreaDetailResponse {
  /**
   *
   * @type {number}
   * @memberof PerformanceAreaDetailResponse
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof PerformanceAreaDetailResponse
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof PerformanceAreaDetailResponse
   */
  grade?: string
  /**
   *
   * @type {number}
   * @memberof PerformanceAreaDetailResponse
   */
  price?: number
  /**
   *
   * @type {number}
   * @memberof PerformanceAreaDetailResponse
   */
  rowCount?: number
  /**
   *
   * @type {number}
   * @memberof PerformanceAreaDetailResponse
   */
  colCount?: number
  /**
   *
   * @type {Array<SeatSimpleResponse>}
   * @memberof PerformanceAreaDetailResponse
   */
  reservedSeats?: Array<SeatSimpleResponse>
}

/**
 * Check if a given object implements the PerformanceAreaDetailResponse interface.
 */
export function instanceOfPerformanceAreaDetailResponse(
  value: object,
): value is PerformanceAreaDetailResponse {
  return true
}

export function PerformanceAreaDetailResponseFromJSON(
  json: any,
): PerformanceAreaDetailResponse {
  return PerformanceAreaDetailResponseFromJSONTyped(json, false)
}

export function PerformanceAreaDetailResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PerformanceAreaDetailResponse {
  if (json == null) {
    return json
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    grade: json["grade"] == null ? undefined : json["grade"],
    price: json["price"] == null ? undefined : json["price"],
    rowCount: json["rowCount"] == null ? undefined : json["rowCount"],
    colCount: json["colCount"] == null ? undefined : json["colCount"],
    reservedSeats:
      json["reservedSeats"] == null
        ? undefined
        : (json["reservedSeats"] as Array<any>).map(SeatSimpleResponseFromJSON),
  }
}

export function PerformanceAreaDetailResponseToJSON(
  json: any,
): PerformanceAreaDetailResponse {
  return PerformanceAreaDetailResponseToJSONTyped(json, false)
}

export function PerformanceAreaDetailResponseToJSONTyped(
  value?: PerformanceAreaDetailResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value["id"],
    name: value["name"],
    grade: value["grade"],
    price: value["price"],
    rowCount: value["rowCount"],
    colCount: value["colCount"],
    reservedSeats:
      value["reservedSeats"] == null
        ? undefined
        : (value["reservedSeats"] as Array<any>).map(SeatSimpleResponseToJSON),
  }
}
