/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceAreaSimpleResponse
 */
export interface PerformanceAreaSimpleResponse {
    /**
     * 
     * @type {number}
     * @memberof PerformanceAreaSimpleResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PerformanceAreaSimpleResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceAreaSimpleResponse
     */
    grade?: string;
    /**
     * 
     * @type {number}
     * @memberof PerformanceAreaSimpleResponse
     */
    price?: number;
}

/**
 * Check if a given object implements the PerformanceAreaSimpleResponse interface.
 */
export function instanceOfPerformanceAreaSimpleResponse(value: object): value is PerformanceAreaSimpleResponse {
    return true;
}

export function PerformanceAreaSimpleResponseFromJSON(json: any): PerformanceAreaSimpleResponse {
    return PerformanceAreaSimpleResponseFromJSONTyped(json, false);
}

export function PerformanceAreaSimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceAreaSimpleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'grade': json['grade'] == null ? undefined : json['grade'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function PerformanceAreaSimpleResponseToJSON(json: any): PerformanceAreaSimpleResponse {
    return PerformanceAreaSimpleResponseToJSONTyped(json, false);
}

export function PerformanceAreaSimpleResponseToJSONTyped(value?: PerformanceAreaSimpleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'grade': value['grade'],
        'price': value['price'],
    };
}

