/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface PostReviewCreateRequest
 */
export interface PostReviewCreateRequest {
  /**
   *
   * @type {number}
   * @memberof PostReviewCreateRequest
   */
  reviewId?: number
  /**
   *
   * @type {string}
   * @memberof PostReviewCreateRequest
   */
  profile?: string
  /**
   *
   * @type {string}
   * @memberof PostReviewCreateRequest
   */
  nickname?: string
  /**
   *
   * @type {string}
   * @memberof PostReviewCreateRequest
   */
  memberId?: string
  /**
   *
   * @type {string}
   * @memberof PostReviewCreateRequest
   */
  content?: string
}

/**
 * Check if a given object implements the PostReviewCreateRequest interface.
 */
export function instanceOfPostReviewCreateRequest(
  value: object,
): value is PostReviewCreateRequest {
  return true
}

export function PostReviewCreateRequestFromJSON(
  json: any,
): PostReviewCreateRequest {
  return PostReviewCreateRequestFromJSONTyped(json, false)
}

export function PostReviewCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PostReviewCreateRequest {
  if (json == null) {
    return json
  }
  return {
    reviewId: json["reviewId"] == null ? undefined : json["reviewId"],
    profile: json["profile"] == null ? undefined : json["profile"],
    nickname: json["nickname"] == null ? undefined : json["nickname"],
    memberId: json["memberId"] == null ? undefined : json["memberId"],
    content: json["content"] == null ? undefined : json["content"],
  }
}

export function PostReviewCreateRequestToJSON(
  json: any,
): PostReviewCreateRequest {
  return PostReviewCreateRequestToJSONTyped(json, false)
}

export function PostReviewCreateRequestToJSONTyped(
  value?: PostReviewCreateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    reviewId: value["reviewId"],
    profile: value["profile"],
    nickname: value["nickname"],
    memberId: value["memberId"],
    content: value["content"],
  }
}
