/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface PostReviewSimpleResponse
 */
export interface PostReviewSimpleResponse {
  /**
   *
   * @type {number}
   * @memberof PostReviewSimpleResponse
   */
  reviewId?: number
  /**
   *
   * @type {string}
   * @memberof PostReviewSimpleResponse
   */
  userId?: string
  /**
   *
   * @type {string}
   * @memberof PostReviewSimpleResponse
   */
  profile?: string
  /**
   *
   * @type {string}
   * @memberof PostReviewSimpleResponse
   */
  nickname?: string
  /**
   *
   * @type {string}
   * @memberof PostReviewSimpleResponse
   */
  content?: string
  /**
   *
   * @type {number}
   * @memberof PostReviewSimpleResponse
   */
  likeCount?: number
}

/**
 * Check if a given object implements the PostReviewSimpleResponse interface.
 */
export function instanceOfPostReviewSimpleResponse(
  value: object,
): value is PostReviewSimpleResponse {
  return true
}

export function PostReviewSimpleResponseFromJSON(
  json: any,
): PostReviewSimpleResponse {
  return PostReviewSimpleResponseFromJSONTyped(json, false)
}

export function PostReviewSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PostReviewSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    reviewId: json["reviewId"] == null ? undefined : json["reviewId"],
    userId: json["userId"] == null ? undefined : json["userId"],
    profile: json["profile"] == null ? undefined : json["profile"],
    nickname: json["nickname"] == null ? undefined : json["nickname"],
    content: json["content"] == null ? undefined : json["content"],
    likeCount: json["likeCount"] == null ? undefined : json["likeCount"],
  }
}

export function PostReviewSimpleResponseToJSON(
  json: any,
): PostReviewSimpleResponse {
  return PostReviewSimpleResponseToJSONTyped(json, false)
}

export function PostReviewSimpleResponseToJSONTyped(
  value?: PostReviewSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    reviewId: value["reviewId"],
    userId: value["userId"],
    profile: value["profile"],
    nickname: value["nickname"],
    content: value["content"],
    likeCount: value["likeCount"],
  }
}
