/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface PostReviewContentRequest
 */
export interface PostReviewContentRequest {
  /**
   *
   * @type {string}
   * @memberof PostReviewContentRequest
   */
  content?: string
}

/**
 * Check if a given object implements the PostReviewContentRequest interface.
 */
export function instanceOfPostReviewContentRequest(
  value: object,
): value is PostReviewContentRequest {
  return true
}

export function PostReviewContentRequestFromJSON(
  json: any,
): PostReviewContentRequest {
  return PostReviewContentRequestFromJSONTyped(json, false)
}

export function PostReviewContentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PostReviewContentRequest {
  if (json == null) {
    return json
  }
  return {
    content: json["content"] == null ? undefined : json["content"],
  }
}

export function PostReviewContentRequestToJSON(
  json: any,
): PostReviewContentRequest {
  return PostReviewContentRequestToJSONTyped(json, false)
}

export function PostReviewContentRequestToJSONTyped(
  value?: PostReviewContentRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    content: value["content"],
  }
}
