/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface PostReviewUpdateRequest
 */
export interface PostReviewUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof PostReviewUpdateRequest
   */
  content?: string
}

/**
 * Check if a given object implements the PostReviewUpdateRequest interface.
 */
export function instanceOfPostReviewUpdateRequest(
  value: object,
): value is PostReviewUpdateRequest {
  return true
}

export function PostReviewUpdateRequestFromJSON(
  json: any,
): PostReviewUpdateRequest {
  return PostReviewUpdateRequestFromJSONTyped(json, false)
}

export function PostReviewUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PostReviewUpdateRequest {
  if (json == null) {
    return json
  }
  return {
    content: json["content"] == null ? undefined : json["content"],
  }
}

export function PostReviewUpdateRequestToJSON(
  json: any,
): PostReviewUpdateRequest {
  return PostReviewUpdateRequestToJSONTyped(json, false)
}

export function PostReviewUpdateRequestToJSONTyped(
  value?: PostReviewUpdateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    content: value["content"],
  }
}
