/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationContext } from './ApplicationContext';
import {
    ApplicationContextFromJSON,
    ApplicationContextFromJSONTyped,
    ApplicationContextToJSON,
    ApplicationContextToJSONTyped,
} from './ApplicationContext';
import type { ServletContext } from './ServletContext';
import {
    ServletContextFromJSON,
    ServletContextFromJSONTyped,
    ServletContextToJSON,
    ServletContextToJSONTyped,
} from './ServletContext';
import type { RedirectViewStatusCode } from './RedirectViewStatusCode';
import {
    RedirectViewStatusCodeFromJSON,
    RedirectViewStatusCodeFromJSONTyped,
    RedirectViewStatusCodeToJSON,
    RedirectViewStatusCodeToJSONTyped,
} from './RedirectViewStatusCode';

/**
 * 
 * @export
 * @interface RedirectView
 */
export interface RedirectView {
    /**
     * 
     * @type {ApplicationContext}
     * @memberof RedirectView
     */
    applicationContext?: ApplicationContext;
    /**
     * 
     * @type {ServletContext}
     * @memberof RedirectView
     */
    servletContext?: ServletContext;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    requestContextAttribute?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof RedirectView
     */
    staticAttributes?: { [key: string]: object; };
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    exposePathVariables?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    exposeContextBeansAsAttributes?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RedirectView
     */
    exposedContextBeanNames?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    beanName?: string;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    contextRelative?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    http10Compatible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    exposeModelAttributes?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    encodingScheme?: string;
    /**
     * 
     * @type {RedirectViewStatusCode}
     * @memberof RedirectView
     */
    statusCode?: RedirectViewStatusCode;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    expandUriTemplateVariables?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    propagateQueryParams?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RedirectView
     */
    hosts?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    redirectView?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectView
     */
    propagateQueryProperties?: boolean;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof RedirectView
     */
    attributesMap?: { [key: string]: object; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RedirectView
     */
    attributes?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof RedirectView
     */
    attributesCSV?: string;
}

/**
 * Check if a given object implements the RedirectView interface.
 */
export function instanceOfRedirectView(value: object): value is RedirectView {
    return true;
}

export function RedirectViewFromJSON(json: any): RedirectView {
    return RedirectViewFromJSONTyped(json, false);
}

export function RedirectViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedirectView {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationContext': json['applicationContext'] == null ? undefined : ApplicationContextFromJSON(json['applicationContext']),
        'servletContext': json['servletContext'] == null ? undefined : ServletContextFromJSON(json['servletContext']),
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'requestContextAttribute': json['requestContextAttribute'] == null ? undefined : json['requestContextAttribute'],
        'staticAttributes': json['staticAttributes'] == null ? undefined : json['staticAttributes'],
        'exposePathVariables': json['exposePathVariables'] == null ? undefined : json['exposePathVariables'],
        'exposeContextBeansAsAttributes': json['exposeContextBeansAsAttributes'] == null ? undefined : json['exposeContextBeansAsAttributes'],
        'exposedContextBeanNames': json['exposedContextBeanNames'] == null ? undefined : json['exposedContextBeanNames'],
        'beanName': json['beanName'] == null ? undefined : json['beanName'],
        'url': json['url'] == null ? undefined : json['url'],
        'contextRelative': json['contextRelative'] == null ? undefined : json['contextRelative'],
        'http10Compatible': json['http10Compatible'] == null ? undefined : json['http10Compatible'],
        'exposeModelAttributes': json['exposeModelAttributes'] == null ? undefined : json['exposeModelAttributes'],
        'encodingScheme': json['encodingScheme'] == null ? undefined : json['encodingScheme'],
        'statusCode': json['statusCode'] == null ? undefined : RedirectViewStatusCodeFromJSON(json['statusCode']),
        'expandUriTemplateVariables': json['expandUriTemplateVariables'] == null ? undefined : json['expandUriTemplateVariables'],
        'propagateQueryParams': json['propagateQueryParams'] == null ? undefined : json['propagateQueryParams'],
        'hosts': json['hosts'] == null ? undefined : json['hosts'],
        'redirectView': json['redirectView'] == null ? undefined : json['redirectView'],
        'propagateQueryProperties': json['propagateQueryProperties'] == null ? undefined : json['propagateQueryProperties'],
        'attributesMap': json['attributesMap'] == null ? undefined : json['attributesMap'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'attributesCSV': json['attributesCSV'] == null ? undefined : json['attributesCSV'],
    };
}

export function RedirectViewToJSON(json: any): RedirectView {
    return RedirectViewToJSONTyped(json, false);
}

export function RedirectViewToJSONTyped(value?: RedirectView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applicationContext': ApplicationContextToJSON(value['applicationContext']),
        'servletContext': ServletContextToJSON(value['servletContext']),
        'contentType': value['contentType'],
        'requestContextAttribute': value['requestContextAttribute'],
        'staticAttributes': value['staticAttributes'],
        'exposePathVariables': value['exposePathVariables'],
        'exposeContextBeansAsAttributes': value['exposeContextBeansAsAttributes'],
        'exposedContextBeanNames': value['exposedContextBeanNames'],
        'beanName': value['beanName'],
        'url': value['url'],
        'contextRelative': value['contextRelative'],
        'http10Compatible': value['http10Compatible'],
        'exposeModelAttributes': value['exposeModelAttributes'],
        'encodingScheme': value['encodingScheme'],
        'statusCode': RedirectViewStatusCodeToJSON(value['statusCode']),
        'expandUriTemplateVariables': value['expandUriTemplateVariables'],
        'propagateQueryParams': value['propagateQueryParams'],
        'hosts': value['hosts'],
        'redirectView': value['redirectView'],
        'propagateQueryProperties': value['propagateQueryProperties'],
        'attributesMap': value['attributesMap'],
        'attributes': value['attributes'],
        'attributesCSV': value['attributesCSV'],
    };
}

