/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DefaultHttpStatusCode } from './DefaultHttpStatusCode';
import {
    instanceOfDefaultHttpStatusCode,
    DefaultHttpStatusCodeFromJSON,
    DefaultHttpStatusCodeFromJSONTyped,
    DefaultHttpStatusCodeToJSON,
} from './DefaultHttpStatusCode';
import type { HttpStatus } from './HttpStatus';
import {
    instanceOfHttpStatus,
    HttpStatusFromJSON,
    HttpStatusFromJSONTyped,
    HttpStatusToJSON,
} from './HttpStatus';

/**
 * @type RedirectViewStatusCode
 * 
 * @export
 */
export type RedirectViewStatusCode = DefaultHttpStatusCode | HttpStatus;

export function RedirectViewStatusCodeFromJSON(json: any): RedirectViewStatusCode {
    return RedirectViewStatusCodeFromJSONTyped(json, false);
}

export function RedirectViewStatusCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedirectViewStatusCode {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDefaultHttpStatusCode(json)) {
        return DefaultHttpStatusCodeFromJSONTyped(json, true);
    }
    if (instanceOfHttpStatus(json)) {
        return HttpStatusFromJSONTyped(json, true);
    }

    return {} as any;
}

export function RedirectViewStatusCodeToJSON(json: any): any {
    return RedirectViewStatusCodeToJSONTyped(json, false);
}

export function RedirectViewStatusCodeToJSONTyped(value?: RedirectViewStatusCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDefaultHttpStatusCode(value)) {
        return DefaultHttpStatusCodeToJSON(value as DefaultHttpStatusCode);
    }
    if (instanceOfHttpStatus(value)) {
        return HttpStatusToJSON(value as HttpStatus);
    }

    return {};
}

