/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeatRequest } from './SeatRequest';
import {
    SeatRequestFromJSON,
    SeatRequestFromJSONTyped,
    SeatRequestToJSON,
    SeatRequestToJSONTyped,
} from './SeatRequest';

/**
 * 
 * @export
 * @interface ReservationCreateRequest
 */
export interface ReservationCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof ReservationCreateRequest
     */
    performanceSessionId?: number;
    /**
     * 
     * @type {Array<SeatRequest>}
     * @memberof ReservationCreateRequest
     */
    seats?: Array<SeatRequest>;
}

/**
 * Check if a given object implements the ReservationCreateRequest interface.
 */
export function instanceOfReservationCreateRequest(value: object): value is ReservationCreateRequest {
    return true;
}

export function ReservationCreateRequestFromJSON(json: any): ReservationCreateRequest {
    return ReservationCreateRequestFromJSONTyped(json, false);
}

export function ReservationCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'performanceSessionId': json['performance_session_id'] == null ? undefined : json['performance_session_id'],
        'seats': json['seats'] == null ? undefined : ((json['seats'] as Array<any>).map(SeatRequestFromJSON)),
    };
}

export function ReservationCreateRequestToJSON(json: any): ReservationCreateRequest {
    return ReservationCreateRequestToJSONTyped(json, false);
}

export function ReservationCreateRequestToJSONTyped(value?: ReservationCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'performance_session_id': value['performanceSessionId'],
        'seats': value['seats'] == null ? undefined : ((value['seats'] as Array<any>).map(SeatRequestToJSON)),
    };
}

