/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { PageResponseMemberSimpleResponse } from "./PageResponseMemberSimpleResponse"
import {
  PageResponseMemberSimpleResponseFromJSON,
  PageResponseMemberSimpleResponseFromJSONTyped,
  PageResponseMemberSimpleResponseToJSON,
  PageResponseMemberSimpleResponseToJSONTyped,
} from "./PageResponseMemberSimpleResponse"

/**
 *
 * @export
 * @interface RsDataPageResponseMemberSimpleResponse
 */
export interface RsDataPageResponseMemberSimpleResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataPageResponseMemberSimpleResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataPageResponseMemberSimpleResponse
   */
  message?: string
  /**
   *
   * @type {PageResponseMemberSimpleResponse}
   * @memberof RsDataPageResponseMemberSimpleResponse
   */
  data?: PageResponseMemberSimpleResponse
}

/**
 * Check if a given object implements the RsDataPageResponseMemberSimpleResponse interface.
 */
export function instanceOfRsDataPageResponseMemberSimpleResponse(
  value: object,
): value is RsDataPageResponseMemberSimpleResponse {
  return true
}

export function RsDataPageResponseMemberSimpleResponseFromJSON(
  json: any,
): RsDataPageResponseMemberSimpleResponse {
  return RsDataPageResponseMemberSimpleResponseFromJSONTyped(json, false)
}

export function RsDataPageResponseMemberSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataPageResponseMemberSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : PageResponseMemberSimpleResponseFromJSON(json["data"]),
  }
}

export function RsDataPageResponseMemberSimpleResponseToJSON(
  json: any,
): RsDataPageResponseMemberSimpleResponse {
  return RsDataPageResponseMemberSimpleResponseToJSONTyped(json, false)
}

export function RsDataPageResponseMemberSimpleResponseToJSONTyped(
  value?: RsDataPageResponseMemberSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data: PageResponseMemberSimpleResponseToJSON(value["data"]),
  }
}
