/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostReviewSimpleResponse } from './PostReviewSimpleResponse';
import {
    PostReviewSimpleResponseFromJSON,
    PostReviewSimpleResponseFromJSONTyped,
    PostReviewSimpleResponseToJSON,
    PostReviewSimpleResponseToJSONTyped,
} from './PostReviewSimpleResponse';

/**
 * 
 * @export
 * @interface RsDataListPostReviewSimpleResponse
 */
export interface RsDataListPostReviewSimpleResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataListPostReviewSimpleResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataListPostReviewSimpleResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<PostReviewSimpleResponse>}
     * @memberof RsDataListPostReviewSimpleResponse
     */
    data?: Array<PostReviewSimpleResponse>;
}

/**
 * Check if a given object implements the RsDataListPostReviewSimpleResponse interface.
 */
export function instanceOfRsDataListPostReviewSimpleResponse(value: object): value is RsDataListPostReviewSimpleResponse {
    return true;
}

export function RsDataListPostReviewSimpleResponseFromJSON(json: any): RsDataListPostReviewSimpleResponse {
    return RsDataListPostReviewSimpleResponseFromJSONTyped(json, false);
}

export function RsDataListPostReviewSimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataListPostReviewSimpleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PostReviewSimpleResponseFromJSON)),
    };
}

export function RsDataListPostReviewSimpleResponseToJSON(json: any): RsDataListPostReviewSimpleResponse {
    return RsDataListPostReviewSimpleResponseToJSONTyped(json, false);
}

export function RsDataListPostReviewSimpleResponseToJSONTyped(value?: RsDataListPostReviewSimpleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PostReviewSimpleResponseToJSON)),
    };
}

