/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { PageResponseExampleSimpleResponse } from "./PageResponseExampleSimpleResponse"
import {
  PageResponseExampleSimpleResponseFromJSON,
  PageResponseExampleSimpleResponseFromJSONTyped,
  PageResponseExampleSimpleResponseToJSON,
  PageResponseExampleSimpleResponseToJSONTyped,
} from "./PageResponseExampleSimpleResponse"

/**
 *
 * @export
 * @interface RsDataPageResponseExampleSimpleResponse
 */
export interface RsDataPageResponseExampleSimpleResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataPageResponseExampleSimpleResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataPageResponseExampleSimpleResponse
   */
  message?: string
  /**
   *
   * @type {PageResponseExampleSimpleResponse}
   * @memberof RsDataPageResponseExampleSimpleResponse
   */
  data?: PageResponseExampleSimpleResponse
}

/**
 * Check if a given object implements the RsDataPageResponseExampleSimpleResponse interface.
 */
export function instanceOfRsDataPageResponseExampleSimpleResponse(
  value: object,
): value is RsDataPageResponseExampleSimpleResponse {
  return true
}

export function RsDataPageResponseExampleSimpleResponseFromJSON(
  json: any,
): RsDataPageResponseExampleSimpleResponse {
  return RsDataPageResponseExampleSimpleResponseFromJSONTyped(json, false)
}

export function RsDataPageResponseExampleSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataPageResponseExampleSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : PageResponseExampleSimpleResponseFromJSON(json["data"]),
  }
}

export function RsDataPageResponseExampleSimpleResponseToJSON(
  json: any,
): RsDataPageResponseExampleSimpleResponse {
  return RsDataPageResponseExampleSimpleResponseToJSONTyped(json, false)
}

export function RsDataPageResponseExampleSimpleResponseToJSONTyped(
  value?: RsDataPageResponseExampleSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data: PageResponseExampleSimpleResponseToJSON(value["data"]),
  }
}
