/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationSimpleResponse } from './ReservationSimpleResponse';
import {
    ReservationSimpleResponseFromJSON,
    ReservationSimpleResponseFromJSONTyped,
    ReservationSimpleResponseToJSON,
    ReservationSimpleResponseToJSONTyped,
} from './ReservationSimpleResponse';

/**
 * 
 * @export
 * @interface RsDataReservationSimpleResponse
 */
export interface RsDataReservationSimpleResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataReservationSimpleResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataReservationSimpleResponse
     */
    message?: string;
    /**
     * 
     * @type {ReservationSimpleResponse}
     * @memberof RsDataReservationSimpleResponse
     */
    data?: ReservationSimpleResponse;
}

/**
 * Check if a given object implements the RsDataReservationSimpleResponse interface.
 */
export function instanceOfRsDataReservationSimpleResponse(value: object): value is RsDataReservationSimpleResponse {
    return true;
}

export function RsDataReservationSimpleResponseFromJSON(json: any): RsDataReservationSimpleResponse {
    return RsDataReservationSimpleResponseFromJSONTyped(json, false);
}

export function RsDataReservationSimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataReservationSimpleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ReservationSimpleResponseFromJSON(json['data']),
    };
}

export function RsDataReservationSimpleResponseToJSON(json: any): RsDataReservationSimpleResponse {
    return RsDataReservationSimpleResponseToJSONTyped(json, false);
}

export function RsDataReservationSimpleResponseToJSONTyped(value?: RsDataReservationSimpleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': ReservationSimpleResponseToJSON(value['data']),
    };
}

