/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { PostSimpleResponse } from "./PostSimpleResponse"
import {
  PostSimpleResponseFromJSON,
  PostSimpleResponseFromJSONTyped,
  PostSimpleResponseToJSON,
  PostSimpleResponseToJSONTyped,
} from "./PostSimpleResponse"

/**
 *
 * @export
 * @interface RsDataListPostSimpleResponse
 */
export interface RsDataListPostSimpleResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataListPostSimpleResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataListPostSimpleResponse
   */
  message?: string
  /**
   *
   * @type {Array<PostSimpleResponse>}
   * @memberof RsDataListPostSimpleResponse
   */
  data?: Array<PostSimpleResponse>
}

/**
 * Check if a given object implements the RsDataListPostSimpleResponse interface.
 */
export function instanceOfRsDataListPostSimpleResponse(
  value: object,
): value is RsDataListPostSimpleResponse {
  return true
}

export function RsDataListPostSimpleResponseFromJSON(
  json: any,
): RsDataListPostSimpleResponse {
  return RsDataListPostSimpleResponseFromJSONTyped(json, false)
}

export function RsDataListPostSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataListPostSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : (json["data"] as Array<any>).map(PostSimpleResponseFromJSON),
  }
}

export function RsDataListPostSimpleResponseToJSON(
  json: any,
): RsDataListPostSimpleResponse {
  return RsDataListPostSimpleResponseToJSONTyped(json, false)
}

export function RsDataListPostSimpleResponseToJSONTyped(
  value?: RsDataListPostSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data:
      value["data"] == null
        ? undefined
        : (value["data"] as Array<any>).map(PostSimpleResponseToJSON),
  }
}
