/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { PerformanceAreaDetailResponse } from "./PerformanceAreaDetailResponse"
import {
  PerformanceAreaDetailResponseFromJSON,
  PerformanceAreaDetailResponseFromJSONTyped,
  PerformanceAreaDetailResponseToJSON,
  PerformanceAreaDetailResponseToJSONTyped,
} from "./PerformanceAreaDetailResponse"

/**
 *
 * @export
 * @interface RsDataListPerformanceAreaDetailResponse
 */
export interface RsDataListPerformanceAreaDetailResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataListPerformanceAreaDetailResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataListPerformanceAreaDetailResponse
   */
  message?: string
  /**
   *
   * @type {Array<PerformanceAreaDetailResponse>}
   * @memberof RsDataListPerformanceAreaDetailResponse
   */
  data?: Array<PerformanceAreaDetailResponse>
}

/**
 * Check if a given object implements the RsDataListPerformanceAreaDetailResponse interface.
 */
export function instanceOfRsDataListPerformanceAreaDetailResponse(
  value: object,
): value is RsDataListPerformanceAreaDetailResponse {
  return true
}

export function RsDataListPerformanceAreaDetailResponseFromJSON(
  json: any,
): RsDataListPerformanceAreaDetailResponse {
  return RsDataListPerformanceAreaDetailResponseFromJSONTyped(json, false)
}

export function RsDataListPerformanceAreaDetailResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataListPerformanceAreaDetailResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : (json["data"] as Array<any>).map(
            PerformanceAreaDetailResponseFromJSON,
          ),
  }
}

export function RsDataListPerformanceAreaDetailResponseToJSON(
  json: any,
): RsDataListPerformanceAreaDetailResponse {
  return RsDataListPerformanceAreaDetailResponseToJSONTyped(json, false)
}

export function RsDataListPerformanceAreaDetailResponseToJSONTyped(
  value?: RsDataListPerformanceAreaDetailResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data:
      value["data"] == null
        ? undefined
        : (value["data"] as Array<any>).map(
            PerformanceAreaDetailResponseToJSON,
          ),
  }
}
