/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostReviewWithLikeResponse } from './PostReviewWithLikeResponse';
import {
    PostReviewWithLikeResponseFromJSON,
    PostReviewWithLikeResponseFromJSONTyped,
    PostReviewWithLikeResponseToJSON,
    PostReviewWithLikeResponseToJSONTyped,
} from './PostReviewWithLikeResponse';

/**
 * 
 * @export
 * @interface RsDataListPostReviewWithLikeResponse
 */
export interface RsDataListPostReviewWithLikeResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataListPostReviewWithLikeResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataListPostReviewWithLikeResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<PostReviewWithLikeResponse>}
     * @memberof RsDataListPostReviewWithLikeResponse
     */
    data?: Array<PostReviewWithLikeResponse>;
}

/**
 * Check if a given object implements the RsDataListPostReviewWithLikeResponse interface.
 */
export function instanceOfRsDataListPostReviewWithLikeResponse(value: object): value is RsDataListPostReviewWithLikeResponse {
    return true;
}

export function RsDataListPostReviewWithLikeResponseFromJSON(json: any): RsDataListPostReviewWithLikeResponse {
    return RsDataListPostReviewWithLikeResponseFromJSONTyped(json, false);
}

export function RsDataListPostReviewWithLikeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataListPostReviewWithLikeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PostReviewWithLikeResponseFromJSON)),
    };
}

export function RsDataListPostReviewWithLikeResponseToJSON(json: any): RsDataListPostReviewWithLikeResponse {
    return RsDataListPostReviewWithLikeResponseToJSONTyped(json, false);
}

export function RsDataListPostReviewWithLikeResponseToJSONTyped(value?: RsDataListPostReviewWithLikeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PostReviewWithLikeResponseToJSON)),
    };
}

