/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentDetailResponse } from './PaymentDetailResponse';
import {
    PaymentDetailResponseFromJSON,
    PaymentDetailResponseFromJSONTyped,
    PaymentDetailResponseToJSON,
    PaymentDetailResponseToJSONTyped,
} from './PaymentDetailResponse';

/**
 * 
 * @export
 * @interface RsDataPaymentDetailResponse
 */
export interface RsDataPaymentDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataPaymentDetailResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataPaymentDetailResponse
     */
    message?: string;
    /**
     * 
     * @type {PaymentDetailResponse}
     * @memberof RsDataPaymentDetailResponse
     */
    data?: PaymentDetailResponse;
}

/**
 * Check if a given object implements the RsDataPaymentDetailResponse interface.
 */
export function instanceOfRsDataPaymentDetailResponse(value: object): value is RsDataPaymentDetailResponse {
    return true;
}

export function RsDataPaymentDetailResponseFromJSON(json: any): RsDataPaymentDetailResponse {
    return RsDataPaymentDetailResponseFromJSONTyped(json, false);
}

export function RsDataPaymentDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataPaymentDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PaymentDetailResponseFromJSON(json['data']),
    };
}

export function RsDataPaymentDetailResponseToJSON(json: any): RsDataPaymentDetailResponse {
    return RsDataPaymentDetailResponseToJSONTyped(json, false);
}

export function RsDataPaymentDetailResponseToJSONTyped(value?: RsDataPaymentDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PaymentDetailResponseToJSON(value['data']),
    };
}

