/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RsDataString
 */
export interface RsDataString {
    /**
     * 
     * @type {number}
     * @memberof RsDataString
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataString
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof RsDataString
     */
    data?: string;
}

/**
 * Check if a given object implements the RsDataString interface.
 */
export function instanceOfRsDataString(value: object): value is RsDataString {
    return true;
}

export function RsDataStringFromJSON(json: any): RsDataString {
    return RsDataStringFromJSONTyped(json, false);
}

export function RsDataStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataString {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function RsDataStringToJSON(json: any): RsDataString {
    return RsDataStringToJSONTyped(json, false);
}

export function RsDataStringToJSONTyped(value?: RsDataString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
    };
}

