/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { ExampleDetailResponse } from "./ExampleDetailResponse"
import {
  ExampleDetailResponseFromJSON,
  ExampleDetailResponseFromJSONTyped,
  ExampleDetailResponseToJSON,
  ExampleDetailResponseToJSONTyped,
} from "./ExampleDetailResponse"

/**
 *
 * @export
 * @interface RsDataExampleDetailResponse
 */
export interface RsDataExampleDetailResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataExampleDetailResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataExampleDetailResponse
   */
  message?: string
  /**
   *
   * @type {ExampleDetailResponse}
   * @memberof RsDataExampleDetailResponse
   */
  data?: ExampleDetailResponse
}

/**
 * Check if a given object implements the RsDataExampleDetailResponse interface.
 */
export function instanceOfRsDataExampleDetailResponse(
  value: object,
): value is RsDataExampleDetailResponse {
  return true
}

export function RsDataExampleDetailResponseFromJSON(
  json: any,
): RsDataExampleDetailResponse {
  return RsDataExampleDetailResponseFromJSONTyped(json, false)
}

export function RsDataExampleDetailResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataExampleDetailResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : ExampleDetailResponseFromJSON(json["data"]),
  }
}

export function RsDataExampleDetailResponseToJSON(
  json: any,
): RsDataExampleDetailResponse {
  return RsDataExampleDetailResponseToJSONTyped(json, false)
}

export function RsDataExampleDetailResponseToJSONTyped(
  value?: RsDataExampleDetailResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data: ExampleDetailResponseToJSON(value["data"]),
  }
}
