/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface RsDataObject
 */
export interface RsDataObject {
  /**
   *
   * @type {number}
   * @memberof RsDataObject
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataObject
   */
  message?: string
  /**
   *
   * @type {object}
   * @memberof RsDataObject
   */
  data?: object
}

/**
 * Check if a given object implements the RsDataObject interface.
 */
export function instanceOfRsDataObject(value: object): value is RsDataObject {
  return true
}

export function RsDataObjectFromJSON(json: any): RsDataObject {
  return RsDataObjectFromJSONTyped(json, false)
}

export function RsDataObjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataObject {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data: json["data"] == null ? undefined : json["data"],
  }
}

export function RsDataObjectToJSON(json: any): RsDataObject {
  return RsDataObjectToJSONTyped(json, false)
}

export function RsDataObjectToJSONTyped(
  value?: RsDataObject | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data: value["data"],
  }
}
