/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostReviewSimpleResponse } from './PostReviewSimpleResponse';
import {
    PostReviewSimpleResponseFromJSON,
    PostReviewSimpleResponseFromJSONTyped,
    PostReviewSimpleResponseToJSON,
    PostReviewSimpleResponseToJSONTyped,
} from './PostReviewSimpleResponse';

/**
 * 
 * @export
 * @interface RsDataPostReviewSimpleResponse
 */
export interface RsDataPostReviewSimpleResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataPostReviewSimpleResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataPostReviewSimpleResponse
     */
    message?: string;
    /**
     * 
     * @type {PostReviewSimpleResponse}
     * @memberof RsDataPostReviewSimpleResponse
     */
    data?: PostReviewSimpleResponse;
}

/**
 * Check if a given object implements the RsDataPostReviewSimpleResponse interface.
 */
export function instanceOfRsDataPostReviewSimpleResponse(value: object): value is RsDataPostReviewSimpleResponse {
    return true;
}

export function RsDataPostReviewSimpleResponseFromJSON(json: any): RsDataPostReviewSimpleResponse {
    return RsDataPostReviewSimpleResponseFromJSONTyped(json, false);
}

export function RsDataPostReviewSimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataPostReviewSimpleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PostReviewSimpleResponseFromJSON(json['data']),
    };
}

export function RsDataPostReviewSimpleResponseToJSON(json: any): RsDataPostReviewSimpleResponse {
    return RsDataPostReviewSimpleResponseToJSONTyped(json, false);
}

export function RsDataPostReviewSimpleResponseToJSONTyped(value?: RsDataPostReviewSimpleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PostReviewSimpleResponseToJSON(value['data']),
    };
}

