/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { PageResponsePaymentLogResponse } from "./PageResponsePaymentLogResponse"
import {
  PageResponsePaymentLogResponseFromJSON,
  PageResponsePaymentLogResponseFromJSONTyped,
  PageResponsePaymentLogResponseToJSON,
  PageResponsePaymentLogResponseToJSONTyped,
} from "./PageResponsePaymentLogResponse"

/**
 *
 * @export
 * @interface RsDataPageResponsePaymentLogResponse
 */
export interface RsDataPageResponsePaymentLogResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataPageResponsePaymentLogResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataPageResponsePaymentLogResponse
   */
  message?: string
  /**
   *
   * @type {PageResponsePaymentLogResponse}
   * @memberof RsDataPageResponsePaymentLogResponse
   */
  data?: PageResponsePaymentLogResponse
}

/**
 * Check if a given object implements the RsDataPageResponsePaymentLogResponse interface.
 */
export function instanceOfRsDataPageResponsePaymentLogResponse(
  value: object,
): value is RsDataPageResponsePaymentLogResponse {
  return true
}

export function RsDataPageResponsePaymentLogResponseFromJSON(
  json: any,
): RsDataPageResponsePaymentLogResponse {
  return RsDataPageResponsePaymentLogResponseFromJSONTyped(json, false)
}

export function RsDataPageResponsePaymentLogResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataPageResponsePaymentLogResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : PageResponsePaymentLogResponseFromJSON(json["data"]),
  }
}

export function RsDataPageResponsePaymentLogResponseToJSON(
  json: any,
): RsDataPageResponsePaymentLogResponse {
  return RsDataPageResponsePaymentLogResponseToJSONTyped(json, false)
}

export function RsDataPageResponsePaymentLogResponseToJSONTyped(
  value?: RsDataPageResponsePaymentLogResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data: PageResponsePaymentLogResponseToJSON(value["data"]),
  }
}
