/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface RsDataLong
 */
export interface RsDataLong {
  /**
   *
   * @type {number}
   * @memberof RsDataLong
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataLong
   */
  message?: string
  /**
   *
   * @type {number}
   * @memberof RsDataLong
   */
  data?: number
}

/**
 * Check if a given object implements the RsDataLong interface.
 */
export function instanceOfRsDataLong(value: object): value is RsDataLong {
  return true
}

export function RsDataLongFromJSON(json: any): RsDataLong {
  return RsDataLongFromJSONTyped(json, false)
}

export function RsDataLongFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataLong {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data: json["data"] == null ? undefined : json["data"],
  }
}

export function RsDataLongToJSON(json: any): RsDataLong {
  return RsDataLongToJSONTyped(json, false)
}

export function RsDataLongToJSONTyped(
  value?: RsDataLong | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data: value["data"],
  }
}
