/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { MemberDetailResponse } from "./MemberDetailResponse"
import {
  MemberDetailResponseFromJSON,
  MemberDetailResponseFromJSONTyped,
  MemberDetailResponseToJSON,
  MemberDetailResponseToJSONTyped,
} from "./MemberDetailResponse"

/**
 *
 * @export
 * @interface RsDataMemberDetailResponse
 */
export interface RsDataMemberDetailResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataMemberDetailResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataMemberDetailResponse
   */
  message?: string
  /**
   *
   * @type {MemberDetailResponse}
   * @memberof RsDataMemberDetailResponse
   */
  data?: MemberDetailResponse
}

/**
 * Check if a given object implements the RsDataMemberDetailResponse interface.
 */
export function instanceOfRsDataMemberDetailResponse(
  value: object,
): value is RsDataMemberDetailResponse {
  return true
}

export function RsDataMemberDetailResponseFromJSON(
  json: any,
): RsDataMemberDetailResponse {
  return RsDataMemberDetailResponseFromJSONTyped(json, false)
}

export function RsDataMemberDetailResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataMemberDetailResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : MemberDetailResponseFromJSON(json["data"]),
  }
}

export function RsDataMemberDetailResponseToJSON(
  json: any,
): RsDataMemberDetailResponse {
  return RsDataMemberDetailResponseToJSONTyped(json, false)
}

export function RsDataMemberDetailResponseToJSONTyped(
  value?: RsDataMemberDetailResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data: MemberDetailResponseToJSON(value["data"]),
  }
}
