/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDetailResponse } from './PostDetailResponse';
import {
    PostDetailResponseFromJSON,
    PostDetailResponseFromJSONTyped,
    PostDetailResponseToJSON,
    PostDetailResponseToJSONTyped,
} from './PostDetailResponse';

/**
 * 
 * @export
 * @interface RsDataPostDetailResponse
 */
export interface RsDataPostDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataPostDetailResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataPostDetailResponse
     */
    message?: string;
    /**
     * 
     * @type {PostDetailResponse}
     * @memberof RsDataPostDetailResponse
     */
    data?: PostDetailResponse;
}

/**
 * Check if a given object implements the RsDataPostDetailResponse interface.
 */
export function instanceOfRsDataPostDetailResponse(value: object): value is RsDataPostDetailResponse {
    return true;
}

export function RsDataPostDetailResponseFromJSON(json: any): RsDataPostDetailResponse {
    return RsDataPostDetailResponseFromJSONTyped(json, false);
}

export function RsDataPostDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataPostDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PostDetailResponseFromJSON(json['data']),
    };
}

export function RsDataPostDetailResponseToJSON(json: any): RsDataPostDetailResponse {
    return RsDataPostDetailResponseToJSONTyped(json, false);
}

export function RsDataPostDetailResponseToJSONTyped(value?: RsDataPostDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PostDetailResponseToJSON(value['data']),
    };
}

