/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { PageResponsePaymentSimpleResponse } from "./PageResponsePaymentSimpleResponse"
import {
  PageResponsePaymentSimpleResponseFromJSON,
  PageResponsePaymentSimpleResponseFromJSONTyped,
  PageResponsePaymentSimpleResponseToJSON,
  PageResponsePaymentSimpleResponseToJSONTyped,
} from "./PageResponsePaymentSimpleResponse"

/**
 *
 * @export
 * @interface RsDataPageResponsePaymentSimpleResponse
 */
export interface RsDataPageResponsePaymentSimpleResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataPageResponsePaymentSimpleResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataPageResponsePaymentSimpleResponse
   */
  message?: string
  /**
   *
   * @type {PageResponsePaymentSimpleResponse}
   * @memberof RsDataPageResponsePaymentSimpleResponse
   */
  data?: PageResponsePaymentSimpleResponse
}

/**
 * Check if a given object implements the RsDataPageResponsePaymentSimpleResponse interface.
 */
export function instanceOfRsDataPageResponsePaymentSimpleResponse(
  value: object,
): value is RsDataPageResponsePaymentSimpleResponse {
  return true
}

export function RsDataPageResponsePaymentSimpleResponseFromJSON(
  json: any,
): RsDataPageResponsePaymentSimpleResponse {
  return RsDataPageResponsePaymentSimpleResponseFromJSONTyped(json, false)
}

export function RsDataPageResponsePaymentSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataPageResponsePaymentSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : PageResponsePaymentSimpleResponseFromJSON(json["data"]),
  }
}

export function RsDataPageResponsePaymentSimpleResponseToJSON(
  json: any,
): RsDataPageResponsePaymentSimpleResponse {
  return RsDataPageResponsePaymentSimpleResponseToJSONTyped(json, false)
}

export function RsDataPageResponsePaymentSimpleResponseToJSONTyped(
  value?: RsDataPageResponsePaymentSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data: PageResponsePaymentSimpleResponseToJSON(value["data"]),
  }
}
