/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
    LoginResponseToJSONTyped,
} from './LoginResponse';

/**
 * 
 * @export
 * @interface RsDataLoginResponse
 */
export interface RsDataLoginResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataLoginResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataLoginResponse
     */
    message?: string;
    /**
     * 
     * @type {LoginResponse}
     * @memberof RsDataLoginResponse
     */
    data?: LoginResponse;
}

/**
 * Check if a given object implements the RsDataLoginResponse interface.
 */
export function instanceOfRsDataLoginResponse(value: object): value is RsDataLoginResponse {
    return true;
}

export function RsDataLoginResponseFromJSON(json: any): RsDataLoginResponse {
    return RsDataLoginResponseFromJSONTyped(json, false);
}

export function RsDataLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : LoginResponseFromJSON(json['data']),
    };
}

export function RsDataLoginResponseToJSON(json: any): RsDataLoginResponse {
    return RsDataLoginResponseToJSONTyped(json, false);
}

export function RsDataLoginResponseToJSONTyped(value?: RsDataLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': LoginResponseToJSON(value['data']),
    };
}

