/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseReservationLogResponse } from './PageResponseReservationLogResponse';
import {
    PageResponseReservationLogResponseFromJSON,
    PageResponseReservationLogResponseFromJSONTyped,
    PageResponseReservationLogResponseToJSON,
    PageResponseReservationLogResponseToJSONTyped,
} from './PageResponseReservationLogResponse';

/**
 * 
 * @export
 * @interface RsDataPageResponseReservationLogResponse
 */
export interface RsDataPageResponseReservationLogResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataPageResponseReservationLogResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataPageResponseReservationLogResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseReservationLogResponse}
     * @memberof RsDataPageResponseReservationLogResponse
     */
    data?: PageResponseReservationLogResponse;
}

/**
 * Check if a given object implements the RsDataPageResponseReservationLogResponse interface.
 */
export function instanceOfRsDataPageResponseReservationLogResponse(value: object): value is RsDataPageResponseReservationLogResponse {
    return true;
}

export function RsDataPageResponseReservationLogResponseFromJSON(json: any): RsDataPageResponseReservationLogResponse {
    return RsDataPageResponseReservationLogResponseFromJSONTyped(json, false);
}

export function RsDataPageResponseReservationLogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataPageResponseReservationLogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageResponseReservationLogResponseFromJSON(json['data']),
    };
}

export function RsDataPageResponseReservationLogResponseToJSON(json: any): RsDataPageResponseReservationLogResponse {
    return RsDataPageResponseReservationLogResponseToJSONTyped(json, false);
}

export function RsDataPageResponseReservationLogResponseToJSONTyped(value?: RsDataPageResponseReservationLogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageResponseReservationLogResponseToJSON(value['data']),
    };
}

