/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationDetailResponse } from './ReservationDetailResponse';
import {
    ReservationDetailResponseFromJSON,
    ReservationDetailResponseFromJSONTyped,
    ReservationDetailResponseToJSON,
    ReservationDetailResponseToJSONTyped,
} from './ReservationDetailResponse';

/**
 * 
 * @export
 * @interface RsDataReservationDetailResponse
 */
export interface RsDataReservationDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataReservationDetailResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataReservationDetailResponse
     */
    message?: string;
    /**
     * 
     * @type {ReservationDetailResponse}
     * @memberof RsDataReservationDetailResponse
     */
    data?: ReservationDetailResponse;
}

/**
 * Check if a given object implements the RsDataReservationDetailResponse interface.
 */
export function instanceOfRsDataReservationDetailResponse(value: object): value is RsDataReservationDetailResponse {
    return true;
}

export function RsDataReservationDetailResponseFromJSON(json: any): RsDataReservationDetailResponse {
    return RsDataReservationDetailResponseFromJSONTyped(json, false);
}

export function RsDataReservationDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataReservationDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ReservationDetailResponseFromJSON(json['data']),
    };
}

export function RsDataReservationDetailResponseToJSON(json: any): RsDataReservationDetailResponse {
    return RsDataReservationDetailResponseToJSONTyped(json, false);
}

export function RsDataReservationDetailResponseToJSONTyped(value?: RsDataReservationDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': ReservationDetailResponseToJSON(value['data']),
    };
}

