/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { PageResponsePostSimpleResponse } from "./PageResponsePostSimpleResponse"
import {
  PageResponsePostSimpleResponseFromJSON,
  PageResponsePostSimpleResponseFromJSONTyped,
  PageResponsePostSimpleResponseToJSON,
  PageResponsePostSimpleResponseToJSONTyped,
} from "./PageResponsePostSimpleResponse"

/**
 *
 * @export
 * @interface RsDataPageResponsePostSimpleResponse
 */
export interface RsDataPageResponsePostSimpleResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataPageResponsePostSimpleResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataPageResponsePostSimpleResponse
   */
  message?: string
  /**
   *
   * @type {PageResponsePostSimpleResponse}
   * @memberof RsDataPageResponsePostSimpleResponse
   */
  data?: PageResponsePostSimpleResponse
}

/**
 * Check if a given object implements the RsDataPageResponsePostSimpleResponse interface.
 */
export function instanceOfRsDataPageResponsePostSimpleResponse(
  value: object,
): value is RsDataPageResponsePostSimpleResponse {
  return true
}

export function RsDataPageResponsePostSimpleResponseFromJSON(
  json: any,
): RsDataPageResponsePostSimpleResponse {
  return RsDataPageResponsePostSimpleResponseFromJSONTyped(json, false)
}

export function RsDataPageResponsePostSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataPageResponsePostSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : PageResponsePostSimpleResponseFromJSON(json["data"]),
  }
}

export function RsDataPageResponsePostSimpleResponseToJSON(
  json: any,
): RsDataPageResponsePostSimpleResponse {
  return RsDataPageResponsePostSimpleResponseToJSONTyped(json, false)
}

export function RsDataPageResponsePostSimpleResponseToJSONTyped(
  value?: RsDataPageResponsePostSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data: PageResponsePostSimpleResponseToJSON(value["data"]),
  }
}
