/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { ExampleSimpleResponse } from "./ExampleSimpleResponse"
import {
  ExampleSimpleResponseFromJSON,
  ExampleSimpleResponseFromJSONTyped,
  ExampleSimpleResponseToJSON,
  ExampleSimpleResponseToJSONTyped,
} from "./ExampleSimpleResponse"

/**
 *
 * @export
 * @interface RsDataListExampleSimpleResponse
 */
export interface RsDataListExampleSimpleResponse {
  /**
   *
   * @type {number}
   * @memberof RsDataListExampleSimpleResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof RsDataListExampleSimpleResponse
   */
  message?: string
  /**
   *
   * @type {Array<ExampleSimpleResponse>}
   * @memberof RsDataListExampleSimpleResponse
   */
  data?: Array<ExampleSimpleResponse>
}

/**
 * Check if a given object implements the RsDataListExampleSimpleResponse interface.
 */
export function instanceOfRsDataListExampleSimpleResponse(
  value: object,
): value is RsDataListExampleSimpleResponse {
  return true
}

export function RsDataListExampleSimpleResponseFromJSON(
  json: any,
): RsDataListExampleSimpleResponse {
  return RsDataListExampleSimpleResponseFromJSONTyped(json, false)
}

export function RsDataListExampleSimpleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RsDataListExampleSimpleResponse {
  if (json == null) {
    return json
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    message: json["message"] == null ? undefined : json["message"],
    data:
      json["data"] == null
        ? undefined
        : (json["data"] as Array<any>).map(ExampleSimpleResponseFromJSON),
  }
}

export function RsDataListExampleSimpleResponseToJSON(
  json: any,
): RsDataListExampleSimpleResponse {
  return RsDataListExampleSimpleResponseToJSONTyped(json, false)
}

export function RsDataListExampleSimpleResponseToJSONTyped(
  value?: RsDataListExampleSimpleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value["code"],
    message: value["message"],
    data:
      value["data"] == null
        ? undefined
        : (value["data"] as Array<any>).map(ExampleSimpleResponseToJSON),
  }
}
