/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenDetailResponse } from './TokenDetailResponse';
import {
    TokenDetailResponseFromJSON,
    TokenDetailResponseFromJSONTyped,
    TokenDetailResponseToJSON,
    TokenDetailResponseToJSONTyped,
} from './TokenDetailResponse';

/**
 * 
 * @export
 * @interface RsDataTokenDetailResponse
 */
export interface RsDataTokenDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof RsDataTokenDetailResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof RsDataTokenDetailResponse
     */
    message?: string;
    /**
     * 
     * @type {TokenDetailResponse}
     * @memberof RsDataTokenDetailResponse
     */
    data?: TokenDetailResponse;
}

/**
 * Check if a given object implements the RsDataTokenDetailResponse interface.
 */
export function instanceOfRsDataTokenDetailResponse(value: object): value is RsDataTokenDetailResponse {
    return true;
}

export function RsDataTokenDetailResponseFromJSON(json: any): RsDataTokenDetailResponse {
    return RsDataTokenDetailResponseFromJSONTyped(json, false);
}

export function RsDataTokenDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsDataTokenDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : TokenDetailResponseFromJSON(json['data']),
    };
}

export function RsDataTokenDetailResponseToJSON(json: any): RsDataTokenDetailResponse {
    return RsDataTokenDetailResponseToJSONTyped(json, false);
}

export function RsDataTokenDetailResponseToJSONTyped(value?: RsDataTokenDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': TokenDetailResponseToJSON(value['data']),
    };
}

