/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface SeatRequest
 */
export interface SeatRequest {
  /**
   *
   * @type {number}
   * @memberof SeatRequest
   */
  areaId?: number
  /**
   *
   * @type {number}
   * @memberof SeatRequest
   */
  row?: number
  /**
   *
   * @type {number}
   * @memberof SeatRequest
   */
  column?: number
}

/**
 * Check if a given object implements the SeatRequest interface.
 */
export function instanceOfSeatRequest(value: object): value is SeatRequest {
  return true
}

export function SeatRequestFromJSON(json: any): SeatRequest {
  return SeatRequestFromJSONTyped(json, false)
}

export function SeatRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SeatRequest {
  if (json == null) {
    return json
  }
  return {
    areaId: json["areaId"] == null ? undefined : json["areaId"],
    row: json["row"] == null ? undefined : json["row"],
    column: json["column"] == null ? undefined : json["column"],
  }
}

export function SeatRequestToJSON(json: any): SeatRequest {
  return SeatRequestToJSONTyped(json, false)
}

export function SeatRequestToJSONTyped(
  value?: SeatRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    areaId: value["areaId"],
    row: value["row"],
    column: value["column"],
  }
}
