/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServletRegistration
 */
export interface ServletRegistration {
    /**
     * 
     * @type {Array<string>}
     * @memberof ServletRegistration
     */
    mappings?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ServletRegistration
     */
    runAsRole?: string;
    /**
     * 
     * @type {string}
     * @memberof ServletRegistration
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServletRegistration
     */
    className?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ServletRegistration
     */
    initParameters?: { [key: string]: string; };
}

/**
 * Check if a given object implements the ServletRegistration interface.
 */
export function instanceOfServletRegistration(value: object): value is ServletRegistration {
    return true;
}

export function ServletRegistrationFromJSON(json: any): ServletRegistration {
    return ServletRegistrationFromJSONTyped(json, false);
}

export function ServletRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServletRegistration {
    if (json == null) {
        return json;
    }
    return {
        
        'mappings': json['mappings'] == null ? undefined : json['mappings'],
        'runAsRole': json['runAsRole'] == null ? undefined : json['runAsRole'],
        'name': json['name'] == null ? undefined : json['name'],
        'className': json['className'] == null ? undefined : json['className'],
        'initParameters': json['initParameters'] == null ? undefined : json['initParameters'],
    };
}

export function ServletRegistrationToJSON(json: any): ServletRegistration {
    return ServletRegistrationToJSONTyped(json, false);
}

export function ServletRegistrationToJSONTyped(value?: ServletRegistration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mappings': value['mappings'],
        'runAsRole': value['runAsRole'],
        'name': value['name'],
        'className': value['className'],
        'initParameters': value['initParameters'],
    };
}

