/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SseEmitter
 */
export interface SseEmitter {
    /**
     * 
     * @type {number}
     * @memberof SseEmitter
     */
    timeout?: number;
}

/**
 * Check if a given object implements the SseEmitter interface.
 */
export function instanceOfSseEmitter(value: object): value is SseEmitter {
    return true;
}

export function SseEmitterFromJSON(json: any): SseEmitter {
    return SseEmitterFromJSONTyped(json, false);
}

export function SseEmitterFromJSONTyped(json: any, ignoreDiscriminator: boolean): SseEmitter {
    if (json == null) {
        return json;
    }
    return {
        
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
    };
}

export function SseEmitterToJSON(json: any): SseEmitter {
    return SseEmitterToJSONTyped(json, false);
}

export function SseEmitterToJSONTyped(value?: SseEmitter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeout': value['timeout'],
    };
}

