/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface TaglibDescriptor
 */
export interface TaglibDescriptor {
  /**
   *
   * @type {string}
   * @memberof TaglibDescriptor
   */
  taglibURI?: string
  /**
   *
   * @type {string}
   * @memberof TaglibDescriptor
   */
  taglibLocation?: string
}

/**
 * Check if a given object implements the TaglibDescriptor interface.
 */
export function instanceOfTaglibDescriptor(
  value: object,
): value is TaglibDescriptor {
  return true
}

export function TaglibDescriptorFromJSON(json: any): TaglibDescriptor {
  return TaglibDescriptorFromJSONTyped(json, false)
}

export function TaglibDescriptorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TaglibDescriptor {
  if (json == null) {
    return json
  }
  return {
    taglibURI: json["taglibURI"] == null ? undefined : json["taglibURI"],
    taglibLocation:
      json["taglibLocation"] == null ? undefined : json["taglibLocation"],
  }
}

export function TaglibDescriptorToJSON(json: any): TaglibDescriptor {
  return TaglibDescriptorToJSONTyped(json, false)
}

export function TaglibDescriptorToJSONTyped(
  value?: TaglibDescriptor | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    taglibURI: value["taglibURI"],
    taglibLocation: value["taglibLocation"],
  }
}
