/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenDetailResponse
 */
export interface TokenDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenDetailResponse
     */
    accessToken?: string;
}

/**
 * Check if a given object implements the TokenDetailResponse interface.
 */
export function instanceOfTokenDetailResponse(value: object): value is TokenDetailResponse {
    return true;
}

export function TokenDetailResponseFromJSON(json: any): TokenDetailResponse {
    return TokenDetailResponseFromJSONTyped(json, false);
}

export function TokenDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
    };
}

export function TokenDetailResponseToJSON(json: any): TokenDetailResponse {
    return TokenDetailResponseToJSONTyped(json, false);
}

export function TokenDetailResponseToJSONTyped(value?: TokenDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
    };
}

