/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileImageRequest
 */
export interface UpdateProfileImageRequest {
    /**
     * 
     * @type {Blob}
     * @memberof UpdateProfileImageRequest
     */
    image: Blob;
}

/**
 * Check if a given object implements the UpdateProfileImageRequest interface.
 */
export function instanceOfUpdateProfileImageRequest(value: object): value is UpdateProfileImageRequest {
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function UpdateProfileImageRequestFromJSON(json: any): UpdateProfileImageRequest {
    return UpdateProfileImageRequestFromJSONTyped(json, false);
}

export function UpdateProfileImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function UpdateProfileImageRequestToJSON(json: any): UpdateProfileImageRequest {
    return UpdateProfileImageRequestToJSONTyped(json, false);
}

export function UpdateProfileImageRequestToJSONTyped(value?: UpdateProfileImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
    };
}

