/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VenueRequest
 */
export interface VenueRequest {
    /**
     * 
     * @type {string}
     * @memberof VenueRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueRequest
     */
    address?: string;
}

/**
 * Check if a given object implements the VenueRequest interface.
 */
export function instanceOfVenueRequest(value: object): value is VenueRequest {
    return true;
}

export function VenueRequestFromJSON(json: any): VenueRequest {
    return VenueRequestFromJSONTyped(json, false);
}

export function VenueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function VenueRequestToJSON(json: any): VenueRequest {
    return VenueRequestToJSONTyped(json, false);
}

export function VenueRequestToJSONTyped(value?: VenueRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
    };
}

