/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface VenueInfo
 */
export interface VenueInfo {
  /**
   *
   * @type {string}
   * @memberof VenueInfo
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof VenueInfo
   */
  address?: string
}

/**
 * Check if a given object implements the VenueInfo interface.
 */
export function instanceOfVenueInfo(value: object): value is VenueInfo {
  return true
}

export function VenueInfoFromJSON(json: any): VenueInfo {
  return VenueInfoFromJSONTyped(json, false)
}

export function VenueInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VenueInfo {
  if (json == null) {
    return json
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    address: json["address"] == null ? undefined : json["address"],
  }
}

export function VenueInfoToJSON(json: any): VenueInfo {
  return VenueInfoToJSONTyped(json, false)
}

export function VenueInfoToJSONTyped(
  value?: VenueInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value["name"],
    address: value["address"],
  }
}
