version: "3.8"

services:
  db:
    image: mysql:8.4.5
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    command: --general-log=1 --general-log-file=/etc/mysql/conf.d/general.log
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_logs:/etc/mysql/conf.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    env_file:
      - .env
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  app:
    image: ghcr.io/prgrms-web-devcourse-final-project/pick-go-app:latest
    container_name: pick-go-app
    restart: always
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


volumes:
  db_data:
  redis_data:
  npm_data:
  npm_letsencrypt:

