global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api.team2.pick-go.shop:8080' ]

  - job_name: 'node'
    static_configs:
      - targets: [ 'api.team2.pick-go.shop:9100' ]