global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'app:8080' ]
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']