/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RsDataPageResponseMemberSimpleResponse,
} from '../models/index';
import {
    RsDataPageResponseMemberSimpleResponseFromJSON,
    RsDataPageResponseMemberSimpleResponseToJSON,
} from '../models/index';

export interface GetMembersRequest {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

/**
 * 
 */
export class AdminAPIApi extends runtime.BaseAPI {

    /**
     * Member 페이징 조회
     */
    async getMembersRaw(requestParameters: GetMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RsDataPageResponseMemberSimpleResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/admin/members`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RsDataPageResponseMemberSimpleResponseFromJSON(jsonValue));
    }

    /**
     * Member 페이징 조회
     */
    async getMembers(requestParameters: GetMembersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RsDataPageResponseMemberSimpleResponse> {
        const response = await this.getMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
