/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime"
import type { RsDataListPerformanceAreaDetailResponse } from "../models/index"
import {
  RsDataListPerformanceAreaDetailResponseFromJSON,
  RsDataListPerformanceAreaDetailResponseToJSON,
} from "../models/index"

export interface GetAreasRequest {
  sessionId: number
}

/**
 *
 */
export class AreaAPIApi extends runtime.BaseAPI {
  /**
   * 구역의 예약중(완료) 좌석 목록을 제공합니다.
   * 구역 목록 조회
   */
  async getAreasRaw(
    requestParameters: GetAreasRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RsDataListPerformanceAreaDetailResponse>> {
    if (requestParameters["sessionId"] == null) {
      throw new runtime.RequiredError(
        "sessionId",
        'Required parameter "sessionId" was null or undefined when calling getAreas().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters["sessionId"] != null) {
      queryParameters["sessionId"] = requestParameters["sessionId"]
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token("Authorization", [])

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/api/areas`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RsDataListPerformanceAreaDetailResponseFromJSON(jsonValue),
    )
  }

  /**
   * 구역의 예약중(완료) 좌석 목록을 제공합니다.
   * 구역 목록 조회
   */
  async getAreas(
    requestParameters: GetAreasRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RsDataListPerformanceAreaDetailResponse> {
    const response = await this.getAreasRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
