/* tslint:disable */
/* eslint-disable */
/**
 * PickGO API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime"
import type {
  ExampleCreateRequest,
  ExampleUpdateRequest,
  RsDataExampleDetailResponse,
  RsDataListExampleSimpleResponse,
  RsDataObject,
  RsDataPageResponseExampleSimpleResponse,
} from "../models/index"
import {
  ExampleCreateRequestFromJSON,
  ExampleCreateRequestToJSON,
  ExampleUpdateRequestFromJSON,
  ExampleUpdateRequestToJSON,
  RsDataExampleDetailResponseFromJSON,
  RsDataExampleDetailResponseToJSON,
  RsDataListExampleSimpleResponseFromJSON,
  RsDataListExampleSimpleResponseToJSON,
  RsDataObjectFromJSON,
  RsDataObjectToJSON,
  RsDataPageResponseExampleSimpleResponseFromJSON,
  RsDataPageResponseExampleSimpleResponseToJSON,
} from "../models/index"

export interface CreateRequest {
  exampleCreateRequest: ExampleCreateRequest
}

export interface GetRequest {
  id: number
}

export interface ListRequest {
  type: ListTypeEnum
  page?: number
  size?: number
  sort?: Array<string>
}

export interface UpdateRequest {
  id: number
  exampleUpdateRequest: ExampleUpdateRequest
}

/**
 *
 */
export class ExampleAPIApi extends runtime.BaseAPI {
  /**
   * Example 생성
   */
  async createRaw(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RsDataExampleDetailResponse>> {
    if (requestParameters["exampleCreateRequest"] == null) {
      throw new runtime.RequiredError(
        "exampleCreateRequest",
        'Required parameter "exampleCreateRequest" was null or undefined when calling create().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token("Authorization", [])

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/api/examples`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: ExampleCreateRequestToJSON(
          requestParameters["exampleCreateRequest"],
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RsDataExampleDetailResponseFromJSON(jsonValue),
    )
  }

  /**
   * Example 생성
   */
  async create(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RsDataExampleDetailResponse> {
    const response = await this.createRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Example id로 조회
   */
  async getRaw(
    requestParameters: GetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RsDataExampleDetailResponse>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling get().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token("Authorization", [])

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/api/examples/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RsDataExampleDetailResponseFromJSON(jsonValue),
    )
  }

  /**
   * Example id로 조회
   */
  async get(
    requestParameters: GetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RsDataExampleDetailResponse> {
    const response = await this.getRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Example 페이징 조회
   */
  async listRaw(
    requestParameters: ListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RsDataPageResponseExampleSimpleResponse>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling list().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"]
    }

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"]
    }

    if (requestParameters["size"] != null) {
      queryParameters["size"] = requestParameters["size"]
    }

    if (requestParameters["sort"] != null) {
      queryParameters["sort"] = requestParameters["sort"]
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token("Authorization", [])

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/api/examples`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RsDataPageResponseExampleSimpleResponseFromJSON(jsonValue),
    )
  }

  /**
   * Example 페이징 조회
   */
  async list(
    requestParameters: ListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RsDataPageResponseExampleSimpleResponse> {
    const response = await this.listRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Example 전체 조회
   */
  async listAllRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RsDataListExampleSimpleResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token("Authorization", [])

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/api/examples/all`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RsDataListExampleSimpleResponseFromJSON(jsonValue),
    )
  }

  /**
   * Example 전체 조회
   */
  async listAll(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RsDataListExampleSimpleResponse> {
    const response = await this.listAllRaw(initOverrides)
    return await response.value()
  }

  /**
   * Example 수정
   */
  async updateRaw(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RsDataObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling update().',
      )
    }

    if (requestParameters["exampleUpdateRequest"] == null) {
      throw new runtime.RequiredError(
        "exampleUpdateRequest",
        'Required parameter "exampleUpdateRequest" was null or undefined when calling update().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token("Authorization", [])

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`
      }
    }
    const response = await this.request(
      {
        path: `/api/examples/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: ExampleUpdateRequestToJSON(
          requestParameters["exampleUpdateRequest"],
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RsDataObjectFromJSON(jsonValue),
    )
  }

  /**
   * Example 수정
   */
  async update(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RsDataObject> {
    const response = await this.updateRaw(requestParameters, initOverrides)
    return await response.value()
  }
}

/**
 * @export
 */
export const ListTypeEnum = {
  A: "A",
  B: "B",
} as const
export type ListTypeEnum = (typeof ListTypeEnum)[keyof typeof ListTypeEnum]
