server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: pickgo
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:dev}
  config:
    import: optional:file:./.env[.properties]
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

custom:
  jwt:
    issuer: ${JWT_ISSUER}
    secret_key: ${JWT_SECRET_KEY}
    access_token:
      expiration_minutes: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:30}
    refresh_token:
      expiration_minutes: ${JWT_REFRESH_TOKEN_EXPIRATION_MINUTES:86400}
    entry_token:
      expiration_minutes: ${JWT_ENTRY_TOKEN_EXPIRATION_MINUTES:10}
    admin_token: ${ADMIN_TOKEN}
    user_token: ${USER_TOKEN}
    expired_token: ${EXPIRED_TOKEN}
    test_entry_token: ${ENTRY_TOKEN}

  http:
    secure: ${HTTP_SECURE:false}

  member:
    profile: ${MEMBER_PROFILE:https://url.kr/estdgi}

  oauth:
    kakao:
      api-key: ${KAKAO_API_KEY}
      redirect-uri: ${KAKAO_LOGIN_REDIRECT_URI:http://localhost:8080/api/oauth/kakao/login/redirect}
      authorize-uri: ${KAKAO_AUTHORIZE_URI:https://kauth.kakao.com/oauth/authorize}
      token-uri: ${KAKAO_TOKEN_URI:https://kauth.kakao.com/oauth/token}
      user-info-uri: ${KAKAO_USER_INFO_URI:https://kapi.kakao.com/v2/user/me}

  toss:
    client_key: ${TOSS_PAYMENT_CLIENT_KEY}
    secret_key: ${TOSS_PAYMENT_SECRET_KEY}

kopis:
  apikey: ${KOPIS_APIKEY}

management:
  endpoints:
    web:
      exposure:
        include: [health, info, prometheus]