server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: pickgo
  profiles:
    active: dev
  config:
    import:
      - optional:file:./.env[.properties]
      - optional:file:./.env.prod[.properties]
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

custom:
  appName: final
  prod:
    domain: pick-go.shop
    backUrl: "https://api.${custom.appName}.${custom.prod.domain}"
    frontUrl: "https://www.${custom.appName}.${custom.prod.domain}"

  dev:
    domain: localhost
    backUrl: "http://${custom.dev.domain}:${server.port}"
    frontUrl: "http://${custom.dev.domain}:3000"