spring:
  jpa:
    hibernate:
      ddl-auto: validate
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    com.example: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO

aws:
  s3:
    bucket: team02-pickgo-prod-bucket
  region: ${AWS_REGION}