spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

custom:
  jwt:
    admin_token: ${ADMIN_TOKEN}
    user_token: ${USER_TOKEN}
    expired_token: ${EXPIRED_TOKEN}