name: PR SpringBoot Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main", "develop"]
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  springboot-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3

      - name: Check for changes in backend folder
        id: check_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend-changed:
              - 'backend/**'

      - name: Navigate to backend directory
        run: cd backend

      - name: Gradle Caching
        if: steps.check_changes.outputs.backend-changed == 'true'
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        if: steps.check_changes.outputs.backend-changed == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        if: steps.check_changes.outputs.backend-changed == 'true'
        run: chmod +x gradlew
        working-directory: backend

      - name: Test with Gradle
        if: steps.check_changes.outputs.backend-changed == 'true'
        run: ./gradlew test
        working-directory: backend
        env:
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          EXPIRED_TOKEN: ${{ secrets.EXPIRED_TOKEN }}
          ENTRY_TOKEN: ${{ secrets.ENTRY_TOKEN }}
          KOPIS_APIKEY: ${{ secrets.KOPIS_APIKEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
          TOSS_PAYMENT_CLIENT_KEY: ${{ secrets.TOSS_PAYMENT_CLIENT_KEY }}
          TOSS_PAYMENT_SECRET_KEY: ${{ secrets.TOSS_PAYMENT_SECRET_KEY }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "backend/**/build/test-results/test/TEST-*.xml"

      - name: Skip backend tests (no changes)
        if: steps.check_changes.outputs.backend-changed == 'false'
        run: echo "No backend changes, skipping tests."
